/** Auto-generated by scripts/extract-hire-landing.mjs */
export const HIRE_LANDING_HERO = {
  "eyebrow": "Dedicated Developers, Aligned with Your Goals",
  "title": "Hire a dedicated development team built for your needs",
  "description": "Expand your team with dedicated developers who integrate smoothly and enhance your project’s success.",
  "image": "https://i.ibb.co.com/bH3K5FL/Rectangle-3843-2x.png",
  "ctaLabel": "Build Your Development Team",
  "ctaHref": "/hire/application-form"
};

export const HIRE_ADVANTAGES_TITLE = "Advantages of the Dedicated Development Team Model";

export const HIRE_ADVANTAGES = [
  {
    "title": "Cost-Efficient and Scalable",
    "description": "Significant savings by eliminating recruitment, infrastructure, and long-term commitments, offering high-quality results within budget."
  },
  {
    "title": "Simplified Talent Acquisition",
    "description": "Significant savings by eliminating recruitment, infrastructure, and long-term commitments, offering high-quality results within budget."
  },
  {
    "title": "Full Transparency and Control",
    "description": "Significant savings by eliminating recruitment, infrastructure, and long-term commitments, offering high-quality results within budget."
  },
  {
    "title": "Aligned with Your Vision",
    "description": "Significant savings by eliminating recruitment, infrastructure, and long-term commitments, offering high-quality results within budget."
  },
  {
    "title": "Flexible Team Management",
    "description": "Easily scale your team based on project demands for short-term or long-term support."
  }
];

export const HIRE_BUILD_TEAM_CTA = {
  "title": "Build Your Team",
  "description": "Need to hire? Contact us to build a skilled team for your needs.",
  "ctaLabel": "Hire Now",
  "ctaHref": "/hire/application-form"
};

export const HIRE_SCENARIOS_TITLE = "Ideal Scenarios for Dedicated Development Team Model";

export const HIRE_SCENARIOS = [
  {
    "tag": "Speed",
    "title": "High Velocity Product Development",
    "description": "Accelerate time-to-market with our specialized offshore IT experts.",
    "bullets": [
      "Rapid product development",
      "Cost-effective scaling",
      "Time zone advantage"
    ],
    "backgroundImage": "https://i.ibb.co.com/DLFqKr5/Rectangle-3841.png"
  },
  {
    "tag": "Expertise",
    "title": "Access to Specialized IT Experts",
    "description": "Leverage top-tier talent for niche and challenging tech projects.",
    "bullets": [
      "Highly skilled offshore teams",
      "Expertise in emerging tech",
      "Global resource availability"
    ],
    "backgroundImage": "https://i.ibb.co.com/Wp6LKzk6/bg-3.png"
  },
  {
    "tag": "Flexibility",
    "title": "Adaptable Offshore Teams",
    "description": "Scale your team as per your project's dynamic needs.",
    "bullets": [
      "On-demand scaling",
      "Diverse tech capabilities",
      "Customized solutions"
    ],
    "backgroundImage": "https://i.ibb.co.com/twTgTLLd/bg-2.png"
  },
  {
    "tag": "Control",
    "title": "Organizations Requiring Managed Offshore IT Experts",
    "description": "Maintain control over development while we handle administrative tasks.",
    "bullets": [
      "Full control over development",
      "Reduced administrative overhead",
      "Efficient resource management"
    ],
    "backgroundImage": "https://i.ibb.co.com/CjS0PVP/bg-1.png"
  }
];
