/** Auto-generated by scripts/extract-tech-stacks.mjs */
export const TECH_STACK_CARDS = [
  {
    "hireLinkName": "frontend-developer",
    "hoverColor": "#006FBA",
    "title": "Frontend Development",
    "description": "Creating responsive and dynamic user interfaces using modern frontend technologies.",
    "technologies": [
      {
        "name": "HTML",
        "image": "/images/html.png"
      },
      {
        "name": "CSS",
        "image": "/images/css.png"
      },
      {
        "name": "JavaScript",
        "image": "/images/js.png"
      },
      {
        "name": "React",
        "image": "/images/react.png"
      },
      {
        "name": "Angular",
        "image": "/images/angular.png"
      },
      {
        "name": "Vue.js",
        "image": "/images/vue.png"
      }
    ]
  },
  {
    "hireLinkName": "backend-developer",
    "hoverColor": "#65308C",
    "title": "Backend Development",
    "description": "Building a robust and scalable backend that supports various features, requirements, and experiences for your users.",
    "technologies": [
      {
        "name": "Node.js",
        "image": "/images/node.png"
      },
      {
        "name": "PHP(Laravel)",
        "image": "/images/laravel.png"
      },
      {
        "name": "Python",
        "image": "/images/python.png"
      },
      {
        "name": "Django",
        "image": "/images/django.png"
      },
      {
        "name": "Ruby",
        "image": "/images/ruby.jpg"
      },
      {
        "name": "Java(Spring)",
        "image": "/images/java.png"
      }
    ]
  },
  {
    "hireLinkName": "mobile-app-developer",
    "hoverColor": "#007F5F",
    "title": "Mobile Development",
    "description": "Developing cross-platform and native mobile apps with cutting-edge frameworks.",
    "technologies": [
      {
        "name": "React Native",
        "image": "/images/react.png"
      },
      {
        "name": "Flutter",
        "image": "/images/flutter.png"
      },
      {
        "name": "Swift",
        "image": "/images/swift.jpg"
      },
      {
        "name": "Kotlin",
        "image": "/images/kotlin.svg"
      },
      {
        "name": "iOS",
        "image": "/images/iOS.png"
      }
    ]
  },
  {
    "hireLinkName": "qa-engineer",
    "hoverColor": "#9A341D",
    "title": "Quality Assurance",
    "description": "Delivering quality applications with advanced testing and QA tools.",
    "technologies": [
      {
        "name": "Selenium",
        "image": "/images/selenium.png"
      },
      {
        "name": "Jest",
        "image": "/images/jest.png"
      },
      {
        "name": "Jmeter",
        "image": "/images/jmeter.png"
      },
      {
        "name": "Postman",
        "image": "/images/postman.png"
      },
      {
        "name": "OWASP",
        "image": "/images/owasp.png"
      }
    ]
  },
  {
    "hireLinkName": "devops-engineer",
    "hoverColor": "#014F43",
    "title": "DevOps",
    "description": "Streamlining development processes and infrastructure with DevOps practices and tools.",
    "technologies": [
      {
        "name": "Docker",
        "image": "/images/docker.webp"
      },
      {
        "name": "Kubernetes",
        "image": "/images/kubernetes.webp"
      },
      {
        "name": "AWS",
        "image": "/images/aws.webp"
      },
      {
        "name": "Azure",
        "image": "/images/Azure.webp"
      },
      {
        "name": "Jenkins",
        "image": "/images/jenkins.webp"
      }
    ]
  },
  {
    "hireLinkName": "ai-ml-developer",
    "hoverColor": "#2C3E50",
    "title": "AI & ML",
    "description": "Leveraging artificial intelligence and machine learning to build smart applications.",
    "technologies": [
      {
        "name": "TensorFlow",
        "image": "/images/tensorflow.webp"
      },
      {
        "name": "PyTorch",
        "image": "/images/pytorch.webp"
      },
      {
        "name": "Keras",
        "image": "/images/keras.webp"
      },
      {
        "name": "Scikit-learn",
        "image": "/images/scikit-learn.webp"
      },
      {
        "name": "OpenCV",
        "image": "/images/opencv.webp"
      }
    ]
  }
];
