/** Auto-generated by scripts/extract-services.mjs */
export const SERVICE_DETAILS = [
  {
    "slug": "custom-software-development",
    "hero": {
      "eyebrow": "CUSTOM SOFTWARE DEVELOPMENT",
      "title": "Transform Your Business with Custom Software Solutions",
      "description": "Our team delivers fintech solutions tailored to industry needs, ensuring compliance, security, and innovation. We leverage AI, blockchain, and cloud computing to develop high-performing applications for the financial sector.",
      "image": "/images/services/custom-software-development-banner-image.webp",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "developing": {
      "title": "Custom Software Development",
      "description": "Tailored, scalable software solutions built to solve your unique business challenges.",
      "image": "/images/services/custom-software.webp",
      "imageAlt": "Custom Software Development",
      "stepsTitle": "Tailored Digital Solutions",
      "steps": [
        {
          "title": "Requirement Analysis",
          "description": "We thoroughly analyze your business needs, technical requirements, and goals to create a tailored software strategy."
        },
        {
          "title": "Solution Architecture",
          "description": "Our team designs a scalable, secure, and modular architecture that aligns with your technical specifications and project needs."
        },
        {
          "title": "Agile Development",
          "description": "We build the solution using agile methodology, delivering incremental updates and continuously improving based on feedback."
        },
        {
          "title": "Testing & Quality Assurance",
          "description": "We conduct thorough unit, integration, and end-to-end testing to ensure your software is stable and bug-free."
        },
        {
          "title": "Deployment & Support",
          "description": "We deploy the solution to production, ensuring complete support, comprehensive documentation, and ongoing post-launch maintenance."
        }
      ],
      "ctaLabel": "Start Custom Project",
      "ctaHref": "/schedule-consultation"
    },
    "whyProcess": {
      "title": "Why Our Process Works?",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-users",
          "title": "Collaborative",
          "description": "We work closely with you at every stage.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-bullseye",
          "title": "Transparent",
          "description": "Regular updates keep you informed.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-rotate",
          "title": "Quality-Focused",
          "description": "Rigorous testing ensures a reliable product.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-code",
          "title": "Scalable",
          "description": "Solutions designed to grow with your business.",
          "variant": "filled"
        }
      ]
    },
    "useCases": {
      "eyebrow": "Use Cases",
      "title": "Boost Efficiency Across Industries",
      "cards": [
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-cart-shopping",
          "title": "Retail",
          "description": "Manage complex shift schedules, ensure labor law compliance, and gain insights to optimize staffing and reduce absenteeism.",
          "bullets": [
            "Employee Scheduling",
            "Compliance",
            "Performance Insights"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-heart-pulse",
          "title": "Healthcare",
          "description": "Efficiently manage rotating shifts, maintain accurate records for billing, and ensure timely emergency coverage.",
          "bullets": [
            "Shift Management",
            "Accurate Records",
            "Emergency Coverage"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-chalkboard-user",
          "title": "Remote Teams",
          "description": "Track attendance and productivity of remote employees, accommodate flexible schedules, and integrate with collaboration tools.",
          "bullets": [
            "Virtual Attendance Tracking",
            "Flexible Scheduling",
            "Integration with Collaboration Tools"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-industry",
          "title": "Manufacturing",
          "description": "Accurately track shifts and overtime, ensure safety compliance, and optimize workforce allocation for production targets.",
          "bullets": [
            "Shift and Overtime Tracking",
            "Safety Compliance",
            "Resource Allocation"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-graduation-cap",
          "title": "Education",
          "description": "Track faculty and student attendance, integrate with management systems, and manage attendance for school events.",
          "bullets": [
            "Faculty and Staff Attendance",
            "Student Attendance",
            "Event Management"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-hand-holding-medical",
          "title": "Hospitality",
          "description": "Efficiently schedule staff for various roles, maintain high guest service standards, and control labor costs.",
          "bullets": [
            "Staff Scheduling",
            "Guest Services",
            "Labor Cost Control"
          ]
        }
      ]
    }
  },
  {
    "slug": "enterprise-software-development",
    "hero": {
      "eyebrow": "ENTERPRISE SOFTWARE DEVELOPMENT",
      "title": "Transform Your Business with Enterprise Software Development",
      "description": "Our team delivers fintech solutions tailored to industry needs, ensuring compliance, security, and innovation. We leverage AI, blockchain, and cloud computing to develop high-performing applications for the financial sector.",
      "image": "/images/services/enterpise-application-development-banner-image.webp",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "developing": {
      "title": "Enterprise Software Development",
      "description": "Designing and building powerful, secure, and scalable software to streamline large-scale enterprise operations.",
      "image": "/images/services/enterprise-software-development.webp",
      "imageAlt": "Enterprise Software Development",
      "stepsTitle": "Scalable Enterprise Solutions",
      "steps": [
        {
          "title": "Enterprise Analysis",
          "description": "Assess business processes, systems, and infrastructure to identify opportunities for digital transformation."
        },
        {
          "title": "System Architecture Design",
          "description": "Create robust and scalable software architecture to support complex enterprise workflows and high availability."
        },
        {
          "title": "Custom Development",
          "description": "Develop tailored solutions with features like automation, data analytics, and ERP integration."
        },
        {
          "title": "Security & Compliance",
          "description": "Implement enterprise-grade security, data protection policies, and industry-specific compliance standards."
        },
        {
          "title": "Deployment & Maintenance",
          "description": "Roll out across departments with full documentation, training, and long-term support for upgrades and scaling."
        }
      ],
      "ctaLabel": "Start Custom Project",
      "ctaHref": "/schedule-consultation"
    },
    "whyProcess": {
      "title": "Why Our Process Works?",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-users",
          "title": "Collaborative",
          "description": "We work closely with you at every stage.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-bullseye",
          "title": "Transparent",
          "description": "Regular updates keep you informed.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-rotate",
          "title": "Quality-Focused",
          "description": "Rigorous testing ensures a reliable product.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-code",
          "title": "Scalable",
          "description": "Solutions designed to grow with your business.",
          "variant": "filled"
        }
      ]
    },
    "useCases": {
      "eyebrow": "Use Cases",
      "title": "Boost Efficiency Across Industries",
      "cards": [
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-cart-shopping",
          "title": "Retail",
          "description": "Manage complex shift schedules, ensure labor law compliance, and gain insights to optimize staffing and reduce absenteeism.",
          "bullets": [
            "Employee Scheduling",
            "Compliance",
            "Performance Insights"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-heart-pulse",
          "title": "Healthcare",
          "description": "Efficiently manage rotating shifts, maintain accurate records for billing, and ensure timely emergency coverage.",
          "bullets": [
            "Shift Management",
            "Accurate Records",
            "Emergency Coverage"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-chalkboard-user",
          "title": "Remote Teams",
          "description": "Track attendance and productivity of remote employees, accommodate flexible schedules, and integrate with collaboration tools.",
          "bullets": [
            "Virtual Attendance Tracking",
            "Flexible Scheduling",
            "Integration with Collaboration Tools"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-industry",
          "title": "Manufacturing",
          "description": "Accurately track shifts and overtime, ensure safety compliance, and optimize workforce allocation for production targets.",
          "bullets": [
            "Shift and Overtime Tracking",
            "Safety Compliance",
            "Resource Allocation"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-graduation-cap",
          "title": "Education",
          "description": "Track faculty and student attendance, integrate with management systems, and manage attendance for school events.",
          "bullets": [
            "Faculty and Staff Attendance",
            "Student Attendance",
            "Event Management"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-hand-holding-medical",
          "title": "Hospitality",
          "description": "Efficiently schedule staff for various roles, maintain high guest service standards, and control labor costs.",
          "bullets": [
            "Staff Scheduling",
            "Guest Services",
            "Labor Cost Control"
          ]
        }
      ]
    }
  },
  {
    "slug": "mobile-app-development",
    "hero": {
      "eyebrow": "MOBILE APP DEVELOPMENT",
      "title": "Transform Your Business with Enterprise Software Development",
      "description": "Our team delivers fintech solutions tailored to industry needs, ensuring compliance, security, and innovation. We leverage AI, blockchain, and cloud computing to develop high-performing applications for the financial sector.",
      "image": "/images/services/mobile-app-development-banner-image.webp",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "developing": {
      "title": "Mobile App Development",
      "description": "Creating high-quality mobile applications for iOS and Android with seamless performance and intuitive UI.",
      "image": "/images/hire/mobile-app.webp",
      "imageAlt": "Mobile App Development",
      "stepsTitle": "iOS & Android Apps",
      "steps": [
        {
          "title": "App Strategy & Planning",
          "description": "Understand business goals, user needs, and define app features, platform, and roadmap."
        },
        {
          "title": "UI/UX Design",
          "description": "Design intuitive and engaging interfaces with a focus on mobile usability and platform guidelines."
        },
        {
          "title": "Cross-Platform or Native Development",
          "description": "Develop high-performance apps using Flutter, React Native, Swift, or Kotlin based on project needs."
        },
        {
          "title": "API & Backend Integration",
          "description": "Connect apps to secure backend systems, databases, and third-party services for complete functionality."
        },
        {
          "title": "Testing & App Store Deployment",
          "description": "Test for performance, security, and bugs before publishing to Google Play and Apple App Store."
        }
      ],
      "ctaLabel": "Start Custom Project",
      "ctaHref": "/schedule-consultation"
    },
    "whyProcess": {
      "title": "Why Our Process Works?",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-users",
          "title": "Collaborative",
          "description": "We work closely with you at every stage.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-bullseye",
          "title": "Transparent",
          "description": "Regular updates keep you informed.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-rotate",
          "title": "Quality-Focused",
          "description": "Rigorous testing ensures a reliable product.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-code",
          "title": "Scalable",
          "description": "Solutions designed to grow with your business.",
          "variant": "filled"
        }
      ]
    },
    "useCases": {
      "eyebrow": "Use Cases",
      "title": "Boost Efficiency Across Industries",
      "cards": [
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-cart-shopping",
          "title": "Retail",
          "description": "Manage complex shift schedules, ensure labor law compliance, and gain insights to optimize staffing and reduce absenteeism.",
          "bullets": [
            "Employee Scheduling",
            "Compliance",
            "Performance Insights"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-heart-pulse",
          "title": "Healthcare",
          "description": "Efficiently manage rotating shifts, maintain accurate records for billing, and ensure timely emergency coverage.",
          "bullets": [
            "Shift Management",
            "Accurate Records",
            "Emergency Coverage"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-chalkboard-user",
          "title": "Remote Teams",
          "description": "Track attendance and productivity of remote employees, accommodate flexible schedules, and integrate with collaboration tools.",
          "bullets": [
            "Virtual Attendance Tracking",
            "Flexible Scheduling",
            "Integration with Collaboration Tools"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-industry",
          "title": "Manufacturing",
          "description": "Accurately track shifts and overtime, ensure safety compliance, and optimize workforce allocation for production targets.",
          "bullets": [
            "Shift and Overtime Tracking",
            "Safety Compliance",
            "Resource Allocation"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-graduation-cap",
          "title": "Education",
          "description": "Track faculty and student attendance, integrate with management systems, and manage attendance for school events.",
          "bullets": [
            "Faculty and Staff Attendance",
            "Student Attendance",
            "Event Management"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-hand-holding-medical",
          "title": "Hospitality",
          "description": "Efficiently schedule staff for various roles, maintain high guest service standards, and control labor costs.",
          "bullets": [
            "Staff Scheduling",
            "Guest Services",
            "Labor Cost Control"
          ]
        }
      ]
    }
  },
  {
    "slug": "mvp-development",
    "hero": {
      "eyebrow": "MVP DEVELOPMENT",
      "title": "Transform Your Business with MVP Development",
      "description": "Our team delivers fintech solutions tailored to industry needs, ensuring compliance, security, and innovation. We leverage AI, blockchain, and cloud computing to develop high-performing applications for the financial sector.",
      "image": "/images/services/mvp-banner-image.webp",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "developing": {
      "title": "MVP Development",
      "description": "Quickly launch a functional version of your product to validate ideas and gather user feedback.",
      "image": "/images/services/mvp.webp",
      "imageAlt": "MVP Development",
      "stepsTitle": "Lean Product Launch",
      "steps": [
        {
          "title": "Discovery & Ideation",
          "description": "We begin by identifying business goals, user problems, and shaping a clear vision for the MVP."
        },
        {
          "title": "Feature Prioritization",
          "description": "We select core features that solve the primary user need while ensuring a lean and valuable product scope."
        },
        {
          "title": "Rapid Prototyping",
          "description": "Our team designs quick wireframes and visual mockups to simulate user flow and validate product direction early."
        },
        {
          "title": "MVP Development",
          "description": "Using agile sprints, we build and test the MVP to deliver a functional version in the shortest time."
        },
        {
          "title": "Launch & Feedback",
          "description": "We release the MVP to real users, collect feedback, and plan iterations based on performance and user input."
        }
      ],
      "ctaLabel": "Start Custom Project",
      "ctaHref": "/schedule-consultation"
    },
    "whyProcess": {
      "title": "Why Our Process Works?",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-users",
          "title": "Collaborative",
          "description": "We work closely with you at every stage.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-bullseye",
          "title": "Transparent",
          "description": "Regular updates keep you informed.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-rotate",
          "title": "Quality-Focused",
          "description": "Rigorous testing ensures a reliable product.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-code",
          "title": "Scalable",
          "description": "Solutions designed to grow with your business.",
          "variant": "filled"
        }
      ]
    },
    "useCases": {
      "eyebrow": "Use Cases",
      "title": "Boost Efficiency Across Industries",
      "cards": [
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-cart-shopping",
          "title": "Retail",
          "description": "Manage complex shift schedules, ensure labor law compliance, and gain insights to optimize staffing and reduce absenteeism.",
          "bullets": [
            "Employee Scheduling",
            "Compliance",
            "Performance Insights"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-heart-pulse",
          "title": "Healthcare",
          "description": "Efficiently manage rotating shifts, maintain accurate records for billing, and ensure timely emergency coverage.",
          "bullets": [
            "Shift Management",
            "Accurate Records",
            "Emergency Coverage"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-chalkboard-user",
          "title": "Remote Teams",
          "description": "Track attendance and productivity of remote employees, accommodate flexible schedules, and integrate with collaboration tools.",
          "bullets": [
            "Virtual Attendance Tracking",
            "Flexible Scheduling",
            "Integration with Collaboration Tools"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-industry",
          "title": "Manufacturing",
          "description": "Accurately track shifts and overtime, ensure safety compliance, and optimize workforce allocation for production targets.",
          "bullets": [
            "Shift and Overtime Tracking",
            "Safety Compliance",
            "Resource Allocation"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-graduation-cap",
          "title": "Education",
          "description": "Track faculty and student attendance, integrate with management systems, and manage attendance for school events.",
          "bullets": [
            "Faculty and Staff Attendance",
            "Student Attendance",
            "Event Management"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-hand-holding-medical",
          "title": "Hospitality",
          "description": "Efficiently schedule staff for various roles, maintain high guest service standards, and control labor costs.",
          "bullets": [
            "Staff Scheduling",
            "Guest Services",
            "Labor Cost Control"
          ]
        }
      ]
    }
  },
  {
    "slug": "qa-and-testing",
    "hero": {
      "eyebrow": "QA & TESTING",
      "title": "Transform Your Business with MVP Development",
      "description": "Our team delivers fintech solutions tailored to industry needs, ensuring compliance, security, and innovation. We leverage AI, blockchain, and cloud computing to develop high-performing applications for the financial sector.",
      "image": "/images/services/qa-testing-banner-image.webp",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "developing": {
      "title": "QA & Testing",
      "description": "Delivering bug-free, high-quality software through manual and automated testing practices.",
      "image": "/images/services/qa-testing.webp",
      "imageAlt": "QA & Testing",
      "stepsTitle": "Quality Assurance",
      "steps": [
        {
          "title": "Requirement Analysis",
          "description": "Understand the application requirements and define the testing scope, types, and strategy."
        },
        {
          "title": "Test Planning",
          "description": "Create test plans, test cases, and determine resources, tools, and environments required."
        },
        {
          "title": "Functional Testing",
          "description": "Ensure all features work as expected through manual and automated functional test cases."
        },
        {
          "title": "Performance & Security Testing",
          "description": "Check the app’s speed, stability under load, and identify vulnerabilities for secure performance."
        },
        {
          "title": "Bug Reporting & Retesting",
          "description": "Log defects, fix bugs, perform regression testing, and prepare detailed QA reports."
        }
      ],
      "ctaLabel": "Start Custom Project",
      "ctaHref": "/schedule-consultation"
    },
    "whyProcess": {
      "title": "Why Our Process Works?",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-users",
          "title": "Collaborative",
          "description": "We work closely with you at every stage.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-bullseye",
          "title": "Transparent",
          "description": "Regular updates keep you informed.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-rotate",
          "title": "Quality-Focused",
          "description": "Rigorous testing ensures a reliable product.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-code",
          "title": "Scalable",
          "description": "Solutions designed to grow with your business.",
          "variant": "filled"
        }
      ]
    },
    "useCases": {
      "eyebrow": "Use Cases",
      "title": "Boost Efficiency Across Industries",
      "cards": [
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-cart-shopping",
          "title": "Retail",
          "description": "Manage complex shift schedules, ensure labor law compliance, and gain insights to optimize staffing and reduce absenteeism.",
          "bullets": [
            "Employee Scheduling",
            "Compliance",
            "Performance Insights"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-heart-pulse",
          "title": "Healthcare",
          "description": "Efficiently manage rotating shifts, maintain accurate records for billing, and ensure timely emergency coverage.",
          "bullets": [
            "Shift Management",
            "Accurate Records",
            "Emergency Coverage"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-chalkboard-user",
          "title": "Remote Teams",
          "description": "Track attendance and productivity of remote employees, accommodate flexible schedules, and integrate with collaboration tools.",
          "bullets": [
            "Virtual Attendance Tracking",
            "Flexible Scheduling",
            "Integration with Collaboration Tools"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-industry",
          "title": "Manufacturing",
          "description": "Accurately track shifts and overtime, ensure safety compliance, and optimize workforce allocation for production targets.",
          "bullets": [
            "Shift and Overtime Tracking",
            "Safety Compliance",
            "Resource Allocation"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-graduation-cap",
          "title": "Education",
          "description": "Track faculty and student attendance, integrate with management systems, and manage attendance for school events.",
          "bullets": [
            "Faculty and Staff Attendance",
            "Student Attendance",
            "Event Management"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-hand-holding-medical",
          "title": "Hospitality",
          "description": "Efficiently schedule staff for various roles, maintain high guest service standards, and control labor costs.",
          "bullets": [
            "Staff Scheduling",
            "Guest Services",
            "Labor Cost Control"
          ]
        }
      ]
    }
  },
  {
    "slug": "team-extension",
    "hero": {
      "eyebrow": "TEAM EXTENSION",
      "title": "Transform Your Business with Team Extension",
      "description": "Our team delivers fintech solutions tailored to industry needs, ensuring compliance, security, and innovation. We leverage AI, blockchain, and cloud computing to develop high-performing applications for the financial sector.",
      "image": "https://i.ibb.co.com/zTXjbc62/Frame-1000005999.png",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "developing": {
      "title": "Team Extension Service",
      "description": "Expand your team with skilled professionals who integrate seamlessly into your workflow.",
      "image": "/images/hire/team-extension.webp",
      "imageAlt": "Team Extension Service",
      "stepsTitle": "Dedicated Developer Teams",
      "steps": [
        {
          "title": "Requirement Gathering",
          "description": "Identify your current team’s gaps, required skills, and the scope of work to build the right extension strategy."
        },
        {
          "title": "Talent Sourcing",
          "description": "Select highly skilled professionals from our pool who align with your tech stack, goals, and culture."
        },
        {
          "title": "Seamless Onboarding",
          "description": "Integrate the selected team members into your workflow with clear communication, tools, and processes."
        },
        {
          "title": "Ongoing Collaboration",
          "description": "Ensure real-time collaboration through daily syncs, task management tools, and transparent reporting."
        },
        {
          "title": "Performance Optimization",
          "description": "Continuously monitor and optimize team performance to ensure quality delivery and scalability."
        }
      ],
      "ctaLabel": "Start Custom Project",
      "ctaHref": "/schedule-consultation"
    },
    "whyProcess": {
      "title": "Why Our Process Works?",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-users",
          "title": "Collaborative",
          "description": "We work closely with you at every stage.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-bullseye",
          "title": "Transparent",
          "description": "Regular updates keep you informed.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-rotate",
          "title": "Quality-Focused",
          "description": "Rigorous testing ensures a reliable product.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-code",
          "title": "Scalable",
          "description": "Solutions designed to grow with your business.",
          "variant": "filled"
        }
      ]
    },
    "useCases": {
      "eyebrow": "Use Cases",
      "title": "Boost Efficiency Across Industries",
      "cards": [
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-cart-shopping",
          "title": "Retail",
          "description": "Manage complex shift schedules, ensure labor law compliance, and gain insights to optimize staffing and reduce absenteeism.",
          "bullets": [
            "Employee Scheduling",
            "Compliance",
            "Performance Insights"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-heart-pulse",
          "title": "Healthcare",
          "description": "Efficiently manage rotating shifts, maintain accurate records for billing, and ensure timely emergency coverage.",
          "bullets": [
            "Shift Management",
            "Accurate Records",
            "Emergency Coverage"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-chalkboard-user",
          "title": "Remote Teams",
          "description": "Track attendance and productivity of remote employees, accommodate flexible schedules, and integrate with collaboration tools.",
          "bullets": [
            "Virtual Attendance Tracking",
            "Flexible Scheduling",
            "Integration with Collaboration Tools"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-industry",
          "title": "Manufacturing",
          "description": "Accurately track shifts and overtime, ensure safety compliance, and optimize workforce allocation for production targets.",
          "bullets": [
            "Shift and Overtime Tracking",
            "Safety Compliance",
            "Resource Allocation"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-graduation-cap",
          "title": "Education",
          "description": "Track faculty and student attendance, integrate with management systems, and manage attendance for school events.",
          "bullets": [
            "Faculty and Staff Attendance",
            "Student Attendance",
            "Event Management"
          ]
        },
        {
          "icon": "group-hover:rotate-[360deg] group-hover:scale-125 transition duration-1000 fa-2x text-[#5856D6] fa-solid fa-hand-holding-medical",
          "title": "Hospitality",
          "description": "Efficiently schedule staff for various roles, maintain high guest service standards, and control labor costs.",
          "bullets": [
            "Staff Scheduling",
            "Guest Services",
            "Labor Cost Control"
          ]
        }
      ]
    }
  }
];
export const SERVICE_SLUGS = [
  "custom-software-development",
  "enterprise-software-development",
  "mobile-app-development",
  "mvp-development",
  "qa-and-testing",
  "team-extension"
];
export function getService(slug: string) {
  return SERVICE_DETAILS.find((s) => s.slug === slug) || null;
}
