/** Auto-generated by scripts/extract-services.mjs */
export const SERVICES_LANDING = {
  "hero": {
    "eyebrow": "Explore Our Services, Built to Drive Your Success",
    "title": "Discover Professional Services for Your Business",
    "description": "We provide expert services to enhance your operations, improve efficiency, and help you achieve your goals.",
    "image": "https://i.ibb.co.com/18ym442/Rectangle-3843.png",
    "ctaLabel": "Book A Consultation",
    "ctaHref": "/schedule-consultation"
  },
  "items": [
    {
      "eyebrow": "Team Extension",
      "title": "Transform Your Business with Team Extension",
      "description": "Expand your development capabilities with dedicated teams that integrate seamlessly with your existing operations.",
      "tags": [
        "Team",
        "Development",
        "Remote"
      ],
      "images": [
        {
          "src": "https://i.ibb.co.com/BzrstK4/Image1.png",
          "alt": "Team Extension1"
        },
        {
          "src": "https://i.ibb.co.com/QdrF5BQ/Image2.png",
          "alt": "Team Extension2"
        },
        {
          "src": "https://i.ibb.co.com/7W1VRHX/Image3.png",
          "alt": "Team Extension3"
        }
      ],
      "href": "/hire",
      "reversed": false
    },
    {
      "eyebrow": "Custom Software Development",
      "title": "Transform Your Business with Custom Software Solutions",
      "description": "Tailored software solutions that align with your business needs, ensuring seamless integration and efficiency.",
      "tags": [
        "Custom",
        "Scalable",
        "Agile"
      ],
      "images": [
        {
          "src": "https://i.ibb.co.com/997tLysb/Adobe-Stock-508936825-resized-1080x675.jpg",
          "alt": "Custom Software Development1"
        },
        {
          "src": "https://i.ibb.co.com/232F2LrY/custom-software-solutions-development.jpg",
          "alt": "Custom Software Development2"
        },
        {
          "src": "https://i.ibb.co.com/HmfCFFz/Custom-Software-Development-1024x538-1.webp",
          "alt": "Custom Software Development3"
        }
      ],
      "href": "/services/services/custom-software-development",
      "reversed": true
    },
    {
      "eyebrow": "Enterprise Software Development",
      "title": "Transform Your Business with Enterprise Software Development",
      "description": "Build robust enterprise-level software to support large-scale operations, improve efficiency, and foster innovation.",
      "tags": [
        "Enterprise",
        "Automation",
        "Scalable"
      ],
      "images": [
        {
          "src": "https://i.ibb.co.com/Y4Ph8ydF/enterprize-1.webp",
          "alt": "Enterprise Software Development1"
        },
        {
          "src": "https://i.ibb.co.com/W4vDqymm/enterprize-2.png",
          "alt": "Enterprise Software Development2"
        },
        {
          "src": "https://i.ibb.co.com/Hj2HCmz/enterprize-3.jpg",
          "alt": "Enterprise Software Development3"
        }
      ],
      "href": "/services/services/enterprise-software-development",
      "reversed": false
    },
    {
      "eyebrow": "Mobile App Development",
      "title": "Transform Your Business with Enterprise Software Development",
      "description": "Design and develop mobile apps for iOS & Android, improving user experience and engagement.",
      "tags": [
        "Mobile",
        "Flutter",
        "React"
      ],
      "images": [
        {
          "src": "https://i.ibb.co.com/qYH97RVF/mobile-app-3.png",
          "alt": "Mobile App Development1"
        },
        {
          "src": "https://i.ibb.co.com/23PSHt2g/mobile-app-2.webp",
          "alt": "Mobile App Development2"
        },
        {
          "src": "https://i.ibb.co.com/mFHjqTj1/mobile-app-1.jpg",
          "alt": "Mobile App Development3"
        }
      ],
      "href": "/services/services/mobile-app-development",
      "reversed": true
    },
    {
      "eyebrow": "Quality Assurance & Testing",
      "title": "Transform Your Business with MVP Development",
      "description": "Ensure software quality with comprehensive testing services, from functional to performance testing.",
      "tags": [
        "Testing",
        "Automation",
        "Security"
      ],
      "images": [
        {
          "src": "https://i.ibb.co.com/dwws7WK9/qa-1.webp",
          "alt": "Quality Assurance & Testing1"
        },
        {
          "src": "https://i.ibb.co.com/TdKNRWz/qa-2.webp",
          "alt": "Quality Assurance & Testing2"
        },
        {
          "src": "https://i.ibb.co.com/gZzGdR6m/qa-3.webp",
          "alt": "Quality Assurance & Testing3"
        }
      ],
      "href": "/services/services/qa-and-testing",
      "reversed": false
    },
    {
      "eyebrow": "MVP Development",
      "title": "Transform Your Business with MVP Development",
      "description": "Build a minimum viable product quickly to test your ideas, validate concepts, and enter the market faster.",
      "tags": [
        "Testing",
        "Automation",
        "Security"
      ],
      "images": [
        {
          "src": "https://i.ibb.co.com/PzrRVmmK/mvp-1.webp",
          "alt": "MVP Development1"
        },
        {
          "src": "https://i.ibb.co.com/7dxNMcJN/mvp-2.webp",
          "alt": "MVP Development2"
        },
        {
          "src": "https://i.ibb.co.com/LDWnHgNG/mvp-3.webp",
          "alt": "MVP Development3"
        }
      ],
      "href": "/services/services/mvp-development",
      "reversed": true
    }
  ]
};
