/** Auto-generated by scripts/extract-industries.mjs */
export const INDUSTRY_DETAILS = [
  {
    "slug": "education",
    "hero": {
      "eyebrow": "EDUCATION",
      "title": "Advancing Education Through Engaging and Scalable Digital Platforms",
      "description": "Our team delivers fintech solutions tailored to industry needs, ensuring compliance, security, and innovation. We leverage AI, blockchain, and cloud computing to develop high-performing applications for the financial sector.",
      "image": "https://i.ibb.co.com/xKxpBqsk/ss.png",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "whyChoose": {
      "title": "Why Choose Us for Education Solutions?",
      "description": "Stay ahead in fintech with secure, scalable solutions. From compliance to AI and blockchain, we drive innovation and growth. Partner with us to transform financial services.",
      "cards": [
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-chart-column",
          "title": "Industry Expertise",
          "description": "Deep understanding of financial regulations and technologies."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-lock",
          "title": "Secure Solutions",
          "description": "Robust security measures to protect sensitive financial data."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-arrow-trend-up",
          "title": "Scalable Platforms",
          "description": "Solutions designed to grow with your business."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-palette",
          "title": "Customer-Centric Design",
          "description": "Focus on delivering seamless user experiences."
        }
      ]
    },
    "expertise": {
      "title": "Our Education Expertise",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-laptop ",
          "title": "E-learning Solutions",
          "description": "Providing online learning platforms.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-chalkboard-teacher ",
          "title": "Teacher Collaboration",
          "description": "Improving collaboration among educators.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-book-open ",
          "title": "Curriculum Development",
          "description": "Designing innovative learning curricula.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-certificate ",
          "title": "Certification Programs",
          "description": "Offering credentialing for online learning.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-users ",
          "title": "Student Engagement",
          "description": "Enhancing student participation and interaction.",
          "variant": "filled"
        }
      ]
    },
    "trends": {
      "title": "Emerging Trends in Education",
      "image": "https://i.ibb.co.com/v4515cNm/57043-1.webp",
      "items": [
        {
          "number": "01",
          "title": "AI & Machine Learning",
          "description": "Artificial Intelligence and Machine Learning are revolutionizing fintech by enabling personalized financial services, predictive analytics, and automated decision-making. From chatbots that enhance customer support to algorithms that detect fraudulent transactions, AI is transforming how financial institutions operate."
        },
        {
          "number": "02",
          "title": "Blockchain & DeFi (Decentralized Finance)",
          "description": "Blockchain technology is powering decentralized finance (DeFi), offering transparent, secure, and trustless financial systems. DeFi platforms enable peer-to-peer lending, decentralized exchanges, and smart contracts, reducing the need for traditional intermediaries like banks."
        },
        {
          "number": "03",
          "title": "Open Banking",
          "description": "Open Banking is reshaping the financial landscape by allowing third-party developers to build applications and services around financial institutions. Through APIs, customers can securely share their financial data, enabling seamless integration of services like budgeting tools, investment platforms, and payment solutions."
        },
        {
          "number": "04",
          "title": "Contactless Payments",
          "description": "Contactless payments are becoming the norm, offering a faster, safer, and more convenient way to transact. With the rise of NFC (Near Field Communication) technology and mobile wallets, consumers can make payments with just a tap, reducing the need for physical cards or cash."
        },
        {
          "number": "05",
          "title": "Embedded Finance",
          "description": "Embedded finance integrates financial services into non-financial platforms, such as e-commerce sites, ride-sharing apps, and retail stores. This trend allows businesses to offer seamless payment options, loans, and insurance directly within their platforms, enhancing customer experience and driving revenue."
        }
      ]
    }
  },
  {
    "slug": "enterprise",
    "hero": {
      "eyebrow": "ENTERPRISE",
      "title": "Powering Enterprises with Scalable, Future-Ready Tech Solutions",
      "description": "Our team delivers enterprise solutions designed to meet the complex demands of modern businesses. We prioritize scalability, data integrity, and seamless integration.",
      "image": "https://i.ibb.co.com/xKxpBqsk/ss.png",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "whyChoose": {
      "title": "Why Choose Us for Enterprise Solutions?",
      "description": "Stay ahead in fintech with secure, scalable solutions. From compliance to AI and blockchain, we drive innovation and growth. Partner with us to transform financial services.",
      "cards": [
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-chart-column",
          "title": "Industry Expertise",
          "description": "Deep understanding of financial regulations and technologies."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-lock",
          "title": "Secure Solutions",
          "description": "Robust security measures to protect sensitive financial data."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-arrow-trend-up",
          "title": "Scalable Platforms",
          "description": "Solutions designed to grow with your business."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-palette",
          "title": "Customer-Centric Design",
          "description": "Focus on delivering seamless user experiences."
        }
      ]
    },
    "expertise": {
      "title": "Our Enterprise Expertise",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-network-wired ",
          "title": "Network Infrastructure",
          "description": "Building robust IT networks for enterprise.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-users-cog ",
          "title": "Enterprise Resource Planning",
          "description": "Integrating business functions with ERP systems.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-chart-bar ",
          "title": "Business Analytics",
          "description": "Leveraging data to drive business decisions.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-lock ",
          "title": "Security Solutions",
          "description": "Providing enterprise-level security services.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-cloud ",
          "title": "Cloud Computing",
          "description": "Empowering businesses with scalable cloud solutions.",
          "variant": "filled"
        }
      ]
    },
    "trends": {
      "title": "Emerging Trends in Enterprise",
      "image": "https://i.ibb.co.com/v4515cNm/57043-1.webp",
      "items": [
        {
          "number": "01",
          "title": "AI & Machine Learning",
          "description": "Artificial Intelligence and Machine Learning are revolutionizing fintech by enabling personalized financial services, predictive analytics, and automated decision-making. From chatbots that enhance customer support to algorithms that detect fraudulent transactions, AI is transforming how financial institutions operate."
        },
        {
          "number": "02",
          "title": "Blockchain & DeFi (Decentralized Finance)",
          "description": "Blockchain technology is powering decentralized finance (DeFi), offering transparent, secure, and trustless financial systems. DeFi platforms enable peer-to-peer lending, decentralized exchanges, and smart contracts, reducing the need for traditional intermediaries like banks."
        },
        {
          "number": "03",
          "title": "Open Banking",
          "description": "Open Banking is reshaping the financial landscape by allowing third-party developers to build applications and services around financial institutions. Through APIs, customers can securely share their financial data, enabling seamless integration of services like budgeting tools, investment platforms, and payment solutions."
        },
        {
          "number": "04",
          "title": "Contactless Payments",
          "description": "Contactless payments are becoming the norm, offering a faster, safer, and more convenient way to transact. With the rise of NFC (Near Field Communication) technology and mobile wallets, consumers can make payments with just a tap, reducing the need for physical cards or cash."
        },
        {
          "number": "05",
          "title": "Embedded Finance",
          "description": "Embedded finance integrates financial services into non-financial platforms, such as e-commerce sites, ride-sharing apps, and retail stores. This trend allows businesses to offer seamless payment options, loans, and insurance directly within their platforms, enhancing customer experience and driving revenue."
        }
      ]
    }
  },
  {
    "slug": "fintech",
    "hero": {
      "eyebrow": "FINTECH",
      "title": "Innovating Financial Services with Secure, Scalable Technology",
      "description": "Our team delivers fintech solutions tailored to industry needs, ensuring compliance, security, and innovation. We leverage AI, blockchain, and cloud computing to develop high-performing applications for the financial sector.",
      "image": "https://i.ibb.co.com/C3vYLnjp/fintech-title-blog.webp",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "whyChoose": {
      "title": "Why Choose Us for Fintech Solutions?",
      "description": "Stay ahead in fintech with secure, scalable solutions. From compliance to AI and blockchain, we drive innovation and growth. Partner with us to transform financial services.",
      "cards": [
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-chart-column",
          "title": "Industry Expertise",
          "description": "Deep understanding of financial regulations and technologies."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-lock",
          "title": "Secure Solutions",
          "description": "Robust security measures to protect sensitive financial data."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-arrow-trend-up",
          "title": "Scalable Platforms",
          "description": "Solutions designed to grow with your business."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-palette",
          "title": "Customer-Centric Design",
          "description": "Focus on delivering seamless user experiences."
        }
      ]
    },
    "expertise": {
      "title": "Our Fintech Expertise",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-regular fa-star",
          "title": "Mortgage Software Development",
          "description": "Custom platforms that automate loan origination and underwriting, improving the borrower journey while ensuring full compliance and scalability.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fa-regular fa-credit-card",
          "title": "Lending Software Development",
          "description": "Build intuitive investment tools featuring real-time analytics, automated portfolio management, and seamless integration with market data sources.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-chart-line",
          "title": "Investment Software Development",
          "description": "End-to-end digital lending solutions that simplify onboarding, credit assessment, and loan management—secure, scalable, and user-focused.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-shield-alt",
          "title": "InsurTech Software Development",
          "description": "Digital insurance platforms that modernize policy management, accelerate claims processing, and enhance customer engagement through automation.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-lock",
          "title": "Payment Software Development Services",
          "description": "Secure, scalable payment systems with multi-currency and gateway support, fraud prevention, and seamless integration.",
          "variant": "filled"
        }
      ]
    },
    "trends": {
      "title": "Emerging Trends in Fintech",
      "image": "https://i.ibb.co.com/v4515cNm/57043-1.webp",
      "items": [
        {
          "number": "01",
          "title": "AI & Machine Learning",
          "description": "Artificial Intelligence and Machine Learning are revolutionizing fintech by enabling personalized financial services, predictive analytics, and automated decision-making. From chatbots that enhance customer support to algorithms that detect fraudulent transactions, AI is transforming how financial institutions operate."
        },
        {
          "number": "02",
          "title": "Blockchain & DeFi (Decentralized Finance)",
          "description": "Blockchain technology is powering decentralized finance (DeFi), offering transparent, secure, and trustless financial systems. DeFi platforms enable peer-to-peer lending, decentralized exchanges, and smart contracts, reducing the need for traditional intermediaries like banks."
        },
        {
          "number": "03",
          "title": "Open Banking",
          "description": "Open Banking is reshaping the financial landscape by allowing third-party developers to build applications and services around financial institutions. Through APIs, customers can securely share their financial data, enabling seamless integration of services like budgeting tools, investment platforms, and payment solutions."
        },
        {
          "number": "04",
          "title": "Contactless Payments",
          "description": "Contactless payments are becoming the norm, offering a faster, safer, and more convenient way to transact. With the rise of NFC (Near Field Communication) technology and mobile wallets, consumers can make payments with just a tap, reducing the need for physical cards or cash."
        },
        {
          "number": "05",
          "title": "Embedded Finance",
          "description": "Embedded finance integrates financial services into non-financial platforms, such as e-commerce sites, ride-sharing apps, and retail stores. This trend allows businesses to offer seamless payment options, loans, and insurance directly within their platforms, enhancing customer experience and driving revenue."
        }
      ]
    }
  },
  {
    "slug": "logistics",
    "hero": {
      "eyebrow": "LOGISTICS",
      "title": "Revolutionizing Logistics with Smart, Real-Time Technology",
      "description": "We deliver logistics solutions that optimize routes, automate workflows, and improve real-time tracking. Powered by AI, IoT, and cloud systems, our tech ensures faster, smarter, and more reliable supply chain operations.",
      "image": "https://i.ibb.co.com/xKxpBqsk/ss.png",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "whyChoose": {
      "title": "Why Choose Us for Logistics Solutions?",
      "description": "Stay ahead in fintech with secure, scalable solutions. From compliance to AI and blockchain, we drive innovation and growth. Partner with us to transform financial services.",
      "cards": [
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-chart-column",
          "title": "Industry Expertise",
          "description": "Deep understanding of financial regulations and technologies."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-lock",
          "title": "Secure Solutions",
          "description": "Robust security measures to protect sensitive financial data."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-arrow-trend-up",
          "title": "Scalable Platforms",
          "description": "Solutions designed to grow with your business."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-palette",
          "title": "Customer-Centric Design",
          "description": "Focus on delivering seamless user experiences."
        }
      ]
    },
    "expertise": {
      "title": "Our Logistics Expertise",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-route ",
          "title": "Supply Chain Management",
          "description": "Optimizing the flow of goods and services.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-truck-moving ",
          "title": "Fleet Management",
          "description": "Managing transportation logistics efficiently.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-box-open ",
          "title": "Inventory Tracking",
          "description": "Monitoring inventory in real-time.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-shipping-fast ",
          "title": "Fast Delivery Solutions",
          "description": "Ensuring on-time delivery to customers.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-chart-line ",
          "title": "Logistics Optimization",
          "description": "Improving operational efficiencies in logistics.",
          "variant": "filled"
        }
      ]
    },
    "trends": {
      "title": "Emerging Trends in Logistics",
      "image": "https://i.ibb.co.com/v4515cNm/57043-1.webp",
      "items": [
        {
          "number": "01",
          "title": "AI & Machine Learning",
          "description": "Artificial Intelligence and Machine Learning are revolutionizing fintech by enabling personalized financial services, predictive analytics, and automated decision-making. From chatbots that enhance customer support to algorithms that detect fraudulent transactions, AI is transforming how financial institutions operate."
        },
        {
          "number": "02",
          "title": "Blockchain & DeFi (Decentralized Finance)",
          "description": "Blockchain technology is powering decentralized finance (DeFi), offering transparent, secure, and trustless financial systems. DeFi platforms enable peer-to-peer lending, decentralized exchanges, and smart contracts, reducing the need for traditional intermediaries like banks."
        },
        {
          "number": "03",
          "title": "Open Banking",
          "description": "Open Banking is reshaping the financial landscape by allowing third-party developers to build applications and services around financial institutions. Through APIs, customers can securely share their financial data, enabling seamless integration of services like budgeting tools, investment platforms, and payment solutions."
        },
        {
          "number": "04",
          "title": "Contactless Payments",
          "description": "Contactless payments are becoming the norm, offering a faster, safer, and more convenient way to transact. With the rise of NFC (Near Field Communication) technology and mobile wallets, consumers can make payments with just a tap, reducing the need for physical cards or cash."
        },
        {
          "number": "05",
          "title": "Embedded Finance",
          "description": "Embedded finance integrates financial services into non-financial platforms, such as e-commerce sites, ride-sharing apps, and retail stores. This trend allows businesses to offer seamless payment options, loans, and insurance directly within their platforms, enhancing customer experience and driving revenue."
        }
      ]
    }
  },
  {
    "slug": "media-and-entertainment",
    "hero": {
      "eyebrow": "MEDIA & ENTERTAINMENT",
      "title": "Driving Media & Entertainment with Interactive Digital Experiences",
      "description": "Our team delivers fintech solutions tailored to industry needs, ensuring compliance, security, and innovation. We leverage AI, blockchain, and cloud computing to develop high-performing applications for the financial sector.",
      "image": "https://i.ibb.co.com/xKxpBqsk/ss.png",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "whyChoose": {
      "title": "Why Choose Us for Media & Entertainment?",
      "description": "Stay ahead in fintech with secure, scalable solutions. From compliance to AI and blockchain, we drive innovation and growth. Partner with us to transform financial services.",
      "cards": [
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-chart-column",
          "title": "Industry Expertise",
          "description": "Deep understanding of financial regulations and technologies."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-lock",
          "title": "Secure Solutions",
          "description": "Robust security measures to protect sensitive financial data."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-arrow-trend-up",
          "title": "Scalable Platforms",
          "description": "Solutions designed to grow with your business."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-palette",
          "title": "Customer-Centric Design",
          "description": "Focus on delivering seamless user experiences."
        }
      ]
    },
    "expertise": {
      "title": "Our Media & Entertainment Expertise",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-video ",
          "title": "Film Production",
          "description": "Producing high-quality films and content.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-headphones-alt ",
          "title": "Music Production",
          "description": "Creating and producing original music.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-camera ",
          "title": "Media Coverage",
          "description": "Providing media coverage and advertising services.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-tv ",
          "title": "Broadcasting",
          "description": "Delivering media content across various platforms.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-play-circle ",
          "title": "Streaming Services",
          "description": "Offering on-demand content to audiences.",
          "variant": "filled"
        }
      ]
    },
    "trends": {
      "title": "Emerging Trends in Media & Entertainment",
      "image": "https://i.ibb.co.com/v4515cNm/57043-1.webp",
      "items": [
        {
          "number": "01",
          "title": "AI & Machine Learning",
          "description": "Artificial Intelligence and Machine Learning are revolutionizing fintech by enabling personalized financial services, predictive analytics, and automated decision-making. From chatbots that enhance customer support to algorithms that detect fraudulent transactions, AI is transforming how financial institutions operate."
        },
        {
          "number": "02",
          "title": "Blockchain & DeFi (Decentralized Finance)",
          "description": "Blockchain technology is powering decentralized finance (DeFi), offering transparent, secure, and trustless financial systems. DeFi platforms enable peer-to-peer lending, decentralized exchanges, and smart contracts, reducing the need for traditional intermediaries like banks."
        },
        {
          "number": "03",
          "title": "Open Banking",
          "description": "Open Banking is reshaping the financial landscape by allowing third-party developers to build applications and services around financial institutions. Through APIs, customers can securely share their financial data, enabling seamless integration of services like budgeting tools, investment platforms, and payment solutions."
        },
        {
          "number": "04",
          "title": "Contactless Payments",
          "description": "Contactless payments are becoming the norm, offering a faster, safer, and more convenient way to transact. With the rise of NFC (Near Field Communication) technology and mobile wallets, consumers can make payments with just a tap, reducing the need for physical cards or cash."
        },
        {
          "number": "05",
          "title": "Embedded Finance",
          "description": "Embedded finance integrates financial services into non-financial platforms, such as e-commerce sites, ride-sharing apps, and retail stores. This trend allows businesses to offer seamless payment options, loans, and insurance directly within their platforms, enhancing customer experience and driving revenue."
        }
      ]
    }
  },
  {
    "slug": "medical-and-healthcare",
    "hero": {
      "eyebrow": "MEDIAL & HEALTHCARE",
      "title": "Enhancing Healthcare with Secure, Compliant Digital Innovation",
      "description": "Our team delivers fintech solutions tailored to industry needs, ensuring compliance, security, and innovation. We leverage AI, blockchain, and cloud computing to develop high-performing applications for the financial sector.",
      "image": "https://i.ibb.co.com/xKxpBqsk/ss.png",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "whyChoose": {
      "title": "Why Choose Us for Mediacal & Healthcare?",
      "description": "Stay ahead in fintech with secure, scalable solutions. From compliance to AI and blockchain, we drive innovation and growth. Partner with us to transform financial services.",
      "cards": [
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-chart-column",
          "title": "Industry Expertise",
          "description": "Deep understanding of financial regulations and technologies."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-lock",
          "title": "Secure Solutions",
          "description": "Robust security measures to protect sensitive financial data."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-arrow-trend-up",
          "title": "Scalable Platforms",
          "description": "Solutions designed to grow with your business."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-palette",
          "title": "Customer-Centric Design",
          "description": "Focus on delivering seamless user experiences."
        }
      ]
    },
    "expertise": {
      "title": "Our Medical & Healthcare Expertise",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-stethoscope ",
          "title": "Telemedicine Solutions",
          "description": "Providing remote healthcare services.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-pills ",
          "title": "Pharmaceutical Services",
          "description": "Offering medical and pharmaceutical support.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-ambulance ",
          "title": "Emergency Care",
          "description": "Ensuring fast and efficient emergency services.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-heart ",
          "title": "Patient Care",
          "description": "Improving patient health and well-being.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-chart-simple ",
          "title": "Health Data Analytics",
          "description": "Using data to enhance healthcare delivery.",
          "variant": "filled"
        }
      ]
    },
    "trends": {
      "title": "Emerging Trends in Medical & Healthcare",
      "image": "https://i.ibb.co.com/v4515cNm/57043-1.webp",
      "items": [
        {
          "number": "01",
          "title": "AI & Machine Learning",
          "description": "Artificial Intelligence and Machine Learning are revolutionizing fintech by enabling personalized financial services, predictive analytics, and automated decision-making. From chatbots that enhance customer support to algorithms that detect fraudulent transactions, AI is transforming how financial institutions operate."
        },
        {
          "number": "02",
          "title": "Blockchain & DeFi (Decentralized Finance)",
          "description": "Blockchain technology is powering decentralized finance (DeFi), offering transparent, secure, and trustless financial systems. DeFi platforms enable peer-to-peer lending, decentralized exchanges, and smart contracts, reducing the need for traditional intermediaries like banks."
        },
        {
          "number": "03",
          "title": "Open Banking",
          "description": "Open Banking is reshaping the financial landscape by allowing third-party developers to build applications and services around financial institutions. Through APIs, customers can securely share their financial data, enabling seamless integration of services like budgeting tools, investment platforms, and payment solutions."
        },
        {
          "number": "04",
          "title": "Contactless Payments",
          "description": "Contactless payments are becoming the norm, offering a faster, safer, and more convenient way to transact. With the rise of NFC (Near Field Communication) technology and mobile wallets, consumers can make payments with just a tap, reducing the need for physical cards or cash."
        },
        {
          "number": "05",
          "title": "Embedded Finance",
          "description": "Embedded finance integrates financial services into non-financial platforms, such as e-commerce sites, ride-sharing apps, and retail stores. This trend allows businesses to offer seamless payment options, loans, and insurance directly within their platforms, enhancing customer experience and driving revenue."
        }
      ]
    }
  },
  {
    "slug": "ngo",
    "hero": {
      "eyebrow": "NGO",
      "title": "Empowering NGOs with Impact-Driven, Scalable Tech Solutions",
      "description": "Our team delivers fintech solutions tailored to industry needs, ensuring compliance, security, and innovation. We leverage AI, blockchain, and cloud computing to develop high-performing applications for the financial sector.",
      "image": "https://i.ibb.co.com/xKxpBqsk/ss.png",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "whyChoose": {
      "title": "Why Choose Us for NGO Solutions?",
      "description": "Stay ahead in fintech with secure, scalable solutions. From compliance to AI and blockchain, we drive innovation and growth. Partner with us to transform financial services.",
      "cards": [
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-chart-column",
          "title": "Industry Expertise",
          "description": "Deep understanding of financial regulations and technologies."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-lock",
          "title": "Secure Solutions",
          "description": "Robust security measures to protect sensitive financial data."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-arrow-trend-up",
          "title": "Scalable Platforms",
          "description": "Solutions designed to grow with your business."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-palette",
          "title": "Customer-Centric Design",
          "description": "Focus on delivering seamless user experiences."
        }
      ]
    },
    "expertise": {
      "title": "Our NGO Expertise",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-donate ",
          "title": "Fundraising",
          "description": "Raising funds to support social causes.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-globe-americas ",
          "title": "Global Outreach",
          "description": "Expanding social impact globally.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-users ",
          "title": "Community Support",
          "description": "Building and supporting local communities.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-hands-helping ",
          "title": "Volunteer Coordination",
          "description": "Engaging volunteers for community projects.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-handshake ",
          "title": "Partnerships",
          "description": "Creating strategic partnerships for social good.",
          "variant": "filled"
        }
      ]
    },
    "trends": {
      "title": "Emerging Trends in NGO",
      "image": "https://i.ibb.co.com/v4515cNm/57043-1.webp",
      "items": [
        {
          "number": "01",
          "title": "AI & Machine Learning",
          "description": "Artificial Intelligence and Machine Learning are revolutionizing fintech by enabling personalized financial services, predictive analytics, and automated decision-making. From chatbots that enhance customer support to algorithms that detect fraudulent transactions, AI is transforming how financial institutions operate."
        },
        {
          "number": "02",
          "title": "Blockchain & DeFi (Decentralized Finance)",
          "description": "Blockchain technology is powering decentralized finance (DeFi), offering transparent, secure, and trustless financial systems. DeFi platforms enable peer-to-peer lending, decentralized exchanges, and smart contracts, reducing the need for traditional intermediaries like banks."
        },
        {
          "number": "03",
          "title": "Open Banking",
          "description": "Open Banking is reshaping the financial landscape by allowing third-party developers to build applications and services around financial institutions. Through APIs, customers can securely share their financial data, enabling seamless integration of services like budgeting tools, investment platforms, and payment solutions."
        },
        {
          "number": "04",
          "title": "Contactless Payments",
          "description": "Contactless payments are becoming the norm, offering a faster, safer, and more convenient way to transact. With the rise of NFC (Near Field Communication) technology and mobile wallets, consumers can make payments with just a tap, reducing the need for physical cards or cash."
        },
        {
          "number": "05",
          "title": "Embedded Finance",
          "description": "Embedded finance integrates financial services into non-financial platforms, such as e-commerce sites, ride-sharing apps, and retail stores. This trend allows businesses to offer seamless payment options, loans, and insurance directly within their platforms, enhancing customer experience and driving revenue."
        }
      ]
    }
  },
  {
    "slug": "real-estate",
    "hero": {
      "eyebrow": "REAL ESTATE",
      "title": "Modernizing Real Estate with Smart, Secure Tech Solutions",
      "description": "Our team delivers fintech solutions tailored to industry needs, ensuring compliance, security, and innovation. We leverage AI, blockchain, and cloud computing to develop high-performing applications for the financial sector.",
      "image": "https://i.ibb.co.com/xKxpBqsk/ss.png",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "whyChoose": {
      "title": "Why Choose Us for Real Estate?",
      "description": "Stay ahead in fintech with secure, scalable solutions. From compliance to AI and blockchain, we drive innovation and growth. Partner with us to transform financial services.",
      "cards": [
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-chart-column",
          "title": "Industry Expertise",
          "description": "Deep understanding of financial regulations and technologies."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-lock",
          "title": "Secure Solutions",
          "description": "Robust security measures to protect sensitive financial data."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-arrow-trend-up",
          "title": "Scalable Platforms",
          "description": "Solutions designed to grow with your business."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-palette",
          "title": "Customer-Centric Design",
          "description": "Focus on delivering seamless user experiences."
        }
      ]
    },
    "expertise": {
      "title": "Our Real Estate Expertise",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-building ",
          "title": "Property Development",
          "description": "Developing and managing residential and commercial properties.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-search ",
          "title": "Market Research",
          "description": "Analyzing market trends and property values.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-handshake ",
          "title": "Investment Opportunities",
          "description": "Connecting investors with profitable properties.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-cogs ",
          "title": "Property Management",
          "description": "Managing real estate properties efficiently.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-chart-line ",
          "title": "Real Estate Analytics",
          "description": "Providing data-driven insights for real estate decisions.",
          "variant": "filled"
        }
      ]
    },
    "trends": {
      "title": "Emerging Trends in Real Estate",
      "image": "https://i.ibb.co.com/v4515cNm/57043-1.webp",
      "items": [
        {
          "number": "01",
          "title": "AI & Machine Learning",
          "description": "Artificial Intelligence and Machine Learning are revolutionizing fintech by enabling personalized financial services, predictive analytics, and automated decision-making. From chatbots that enhance customer support to algorithms that detect fraudulent transactions, AI is transforming how financial institutions operate."
        },
        {
          "number": "02",
          "title": "Blockchain & DeFi (Decentralized Finance)",
          "description": "Blockchain technology is powering decentralized finance (DeFi), offering transparent, secure, and trustless financial systems. DeFi platforms enable peer-to-peer lending, decentralized exchanges, and smart contracts, reducing the need for traditional intermediaries like banks."
        },
        {
          "number": "03",
          "title": "Open Banking",
          "description": "Open Banking is reshaping the financial landscape by allowing third-party developers to build applications and services around financial institutions. Through APIs, customers can securely share their financial data, enabling seamless integration of services like budgeting tools, investment platforms, and payment solutions."
        },
        {
          "number": "04",
          "title": "Contactless Payments",
          "description": "Contactless payments are becoming the norm, offering a faster, safer, and more convenient way to transact. With the rise of NFC (Near Field Communication) technology and mobile wallets, consumers can make payments with just a tap, reducing the need for physical cards or cash."
        },
        {
          "number": "05",
          "title": "Embedded Finance",
          "description": "Embedded finance integrates financial services into non-financial platforms, such as e-commerce sites, ride-sharing apps, and retail stores. This trend allows businesses to offer seamless payment options, loans, and insurance directly within their platforms, enhancing customer experience and driving revenue."
        }
      ]
    }
  },
  {
    "slug": "retail-and-manufacturing",
    "hero": {
      "eyebrow": "RETAIL & MANUFACTURING",
      "title": "Transforming Retail & Manufacturing with Intelligent Automation",
      "description": "We build smart retail and manufacturing solutions that boost efficiency, streamline operations, and enhance customer experiences. Using IoT, AI, and cloud technologies, we help businesses stay agile and competitive in a fast-evolving market.",
      "image": "https://i.ibb.co.com/xKxpBqsk/ss.png",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "whyChoose": {
      "title": "Why Choose Us for Retail & Manufacturing?",
      "description": "Stay ahead in fintech with secure, scalable solutions. From compliance to AI and blockchain, we drive innovation and growth. Partner with us to transform financial services.",
      "cards": [
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-chart-column",
          "title": "Industry Expertise",
          "description": "Deep understanding of financial regulations and technologies."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-lock",
          "title": "Secure Solutions",
          "description": "Robust security measures to protect sensitive financial data."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-arrow-trend-up",
          "title": "Scalable Platforms",
          "description": "Solutions designed to grow with your business."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-palette",
          "title": "Customer-Centric Design",
          "description": "Focus on delivering seamless user experiences."
        }
      ]
    },
    "expertise": {
      "title": "Our Retail & Manufacturing Expertise",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-cogs ",
          "title": "Manufacturing Optimization",
          "description": "Streamlining production processes.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-tags ",
          "title": "Retail Management",
          "description": "Managing retail operations effectively.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-truck-loading ",
          "title": "Supply Chain Solutions",
          "description": "Ensuring smooth product flow.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-box ",
          "title": "Product Packaging",
          "description": "Enhancing packaging solutions for retail.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-percent ",
          "title": "Sales Growth",
          "description": "Driving revenue through retail strategies.",
          "variant": "filled"
        }
      ]
    },
    "trends": {
      "title": "Emerging Trends in Retail & Manufacturing",
      "image": "https://i.ibb.co.com/v4515cNm/57043-1.webp",
      "items": [
        {
          "number": "01",
          "title": "AI & Machine Learning",
          "description": "Artificial Intelligence and Machine Learning are revolutionizing fintech by enabling personalized financial services, predictive analytics, and automated decision-making. From chatbots that enhance customer support to algorithms that detect fraudulent transactions, AI is transforming how financial institutions operate."
        },
        {
          "number": "02",
          "title": "Blockchain & DeFi (Decentralized Finance)",
          "description": "Blockchain technology is powering decentralized finance (DeFi), offering transparent, secure, and trustless financial systems. DeFi platforms enable peer-to-peer lending, decentralized exchanges, and smart contracts, reducing the need for traditional intermediaries like banks."
        },
        {
          "number": "03",
          "title": "Open Banking",
          "description": "Open Banking is reshaping the financial landscape by allowing third-party developers to build applications and services around financial institutions. Through APIs, customers can securely share their financial data, enabling seamless integration of services like budgeting tools, investment platforms, and payment solutions."
        },
        {
          "number": "04",
          "title": "Contactless Payments",
          "description": "Contactless payments are becoming the norm, offering a faster, safer, and more convenient way to transact. With the rise of NFC (Near Field Communication) technology and mobile wallets, consumers can make payments with just a tap, reducing the need for physical cards or cash."
        },
        {
          "number": "05",
          "title": "Embedded Finance",
          "description": "Embedded finance integrates financial services into non-financial platforms, such as e-commerce sites, ride-sharing apps, and retail stores. This trend allows businesses to offer seamless payment options, loans, and insurance directly within their platforms, enhancing customer experience and driving revenue."
        }
      ]
    }
  },
  {
    "slug": "startup",
    "hero": {
      "eyebrow": "STARTUP",
      "title": "Fueling Startup Growth with Agile, Scalable Digital Solutions",
      "description": "We empower startups with agile, scalable solutions tailored for rapid growth. From MVP development to full-scale products, we use modern tech stacks to turn bold ideas into successful digital products—fast and efficiently.",
      "image": "https://i.ibb.co.com/xKxpBqsk/ss.png",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "whyChoose": {
      "title": "Why Choose Us for Startup Solutions?",
      "description": "Stay ahead in fintech with secure, scalable solutions. From compliance to AI and blockchain, we drive innovation and growth. Partner with us to transform financial services.",
      "cards": [
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-chart-column",
          "title": "Industry Expertise",
          "description": "Deep understanding of financial regulations and technologies."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-lock",
          "title": "Secure Solutions",
          "description": "Robust security measures to protect sensitive financial data."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-arrow-trend-up",
          "title": "Scalable Platforms",
          "description": "Solutions designed to grow with your business."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-palette",
          "title": "Customer-Centric Design",
          "description": "Focus on delivering seamless user experiences."
        }
      ]
    },
    "expertise": {
      "title": "Our Startup Expertise",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-users ",
          "title": "Team Building",
          "description": "Assembling innovative teams for success.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-bullhorn ",
          "title": "Brand Awareness",
          "description": "Creating strong brand recognition in the market.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-chart-pie ",
          "title": "Market Strategy",
          "description": "Identifying and targeting the right market.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-cogs ",
          "title": "Product Development",
          "description": "Turning ideas into functional products.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-hand-holding-usd ",
          "title": "Investment & Funding",
          "description": "Securing capital for business growth.",
          "variant": "filled"
        }
      ]
    },
    "trends": {
      "title": "Emerging Trends in Startup",
      "image": "https://i.ibb.co.com/v4515cNm/57043-1.webp",
      "items": [
        {
          "number": "01",
          "title": "AI & Machine Learning",
          "description": "Artificial Intelligence and Machine Learning are revolutionizing fintech by enabling personalized financial services, predictive analytics, and automated decision-making. From chatbots that enhance customer support to algorithms that detect fraudulent transactions, AI is transforming how financial institutions operate."
        },
        {
          "number": "02",
          "title": "Blockchain & DeFi (Decentralized Finance)",
          "description": "Blockchain technology is powering decentralized finance (DeFi), offering transparent, secure, and trustless financial systems. DeFi platforms enable peer-to-peer lending, decentralized exchanges, and smart contracts, reducing the need for traditional intermediaries like banks."
        },
        {
          "number": "03",
          "title": "Open Banking",
          "description": "Open Banking is reshaping the financial landscape by allowing third-party developers to build applications and services around financial institutions. Through APIs, customers can securely share their financial data, enabling seamless integration of services like budgeting tools, investment platforms, and payment solutions."
        },
        {
          "number": "04",
          "title": "Contactless Payments",
          "description": "Contactless payments are becoming the norm, offering a faster, safer, and more convenient way to transact. With the rise of NFC (Near Field Communication) technology and mobile wallets, consumers can make payments with just a tap, reducing the need for physical cards or cash."
        },
        {
          "number": "05",
          "title": "Embedded Finance",
          "description": "Embedded finance integrates financial services into non-financial platforms, such as e-commerce sites, ride-sharing apps, and retail stores. This trend allows businesses to offer seamless payment options, loans, and insurance directly within their platforms, enhancing customer experience and driving revenue."
        }
      ]
    }
  },
  {
    "slug": "technology-company",
    "hero": {
      "eyebrow": "TECHNOLOGY COMPANY",
      "title": "Accelerating Tech Innovation with Custom, Scalable Development",
      "description": "Our team delivers fintech solutions tailored to industry needs, ensuring compliance, security, and innovation. We leverage AI, blockchain, and cloud computing to develop high-performing applications for the financial sector.",
      "image": "https://i.ibb.co.com/xKxpBqsk/ss.png",
      "ctaLabel": "Book A Consulation",
      "ctaHref": "/schedule-consultation"
    },
    "whyChoose": {
      "title": "Why Choose Us for Technology Company?",
      "description": "Stay ahead in fintech with secure, scalable solutions. From compliance to AI and blockchain, we drive innovation and growth. Partner with us to transform financial services.",
      "cards": [
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-chart-column",
          "title": "Industry Expertise",
          "description": "Deep understanding of financial regulations and technologies."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-lock",
          "title": "Secure Solutions",
          "description": "Robust security measures to protect sensitive financial data."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-arrow-trend-up",
          "title": "Scalable Platforms",
          "description": "Solutions designed to grow with your business."
        },
        {
          "icon": "text-3xl absolute top-6 right-6 fa-solid fa-palette",
          "title": "Customer-Centric Design",
          "description": "Focus on delivering seamless user experiences."
        }
      ]
    },
    "expertise": {
      "title": "Our Technology Company Expertise",
      "cards": [
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-code ",
          "title": "Software Development",
          "description": "Building custom software solutions for businesses.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-cloud ",
          "title": "Cloud Solutions",
          "description": "Enabling businesses with scalable cloud computing.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-digital-tachograph ",
          "title": "Tech Consulting",
          "description": "Providing expert guidance for technology adoption.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-mobile-alt ",
          "title": "Mobile Development",
          "description": "Creating mobile applications for various platforms.",
          "variant": "filled"
        },
        {
          "icon": "transition-transform transform group-hover:scale-150 duration-500 fa-xl lg:text-3xl text-[#5856d6] fa-solid fas fa-network-wired ",
          "title": "IT Infrastructure",
          "description": "Designing and implementing tech infrastructures.",
          "variant": "filled"
        }
      ]
    },
    "trends": {
      "title": "Emerging Trends in Technology Company",
      "image": "https://i.ibb.co.com/v4515cNm/57043-1.webp",
      "items": [
        {
          "number": "01",
          "title": "AI & Machine Learning",
          "description": "Artificial Intelligence and Machine Learning are revolutionizing fintech by enabling personalized financial services, predictive analytics, and automated decision-making. From chatbots that enhance customer support to algorithms that detect fraudulent transactions, AI is transforming how financial institutions operate."
        },
        {
          "number": "02",
          "title": "Blockchain & DeFi (Decentralized Finance)",
          "description": "Blockchain technology is powering decentralized finance (DeFi), offering transparent, secure, and trustless financial systems. DeFi platforms enable peer-to-peer lending, decentralized exchanges, and smart contracts, reducing the need for traditional intermediaries like banks."
        },
        {
          "number": "03",
          "title": "Open Banking",
          "description": "Open Banking is reshaping the financial landscape by allowing third-party developers to build applications and services around financial institutions. Through APIs, customers can securely share their financial data, enabling seamless integration of services like budgeting tools, investment platforms, and payment solutions."
        },
        {
          "number": "04",
          "title": "Contactless Payments",
          "description": "Contactless payments are becoming the norm, offering a faster, safer, and more convenient way to transact. With the rise of NFC (Near Field Communication) technology and mobile wallets, consumers can make payments with just a tap, reducing the need for physical cards or cash."
        },
        {
          "number": "05",
          "title": "Embedded Finance",
          "description": "Embedded finance integrates financial services into non-financial platforms, such as e-commerce sites, ride-sharing apps, and retail stores. This trend allows businesses to offer seamless payment options, loans, and insurance directly within their platforms, enhancing customer experience and driving revenue."
        }
      ]
    }
  }
];
export const INDUSTRY_SLUGS = [
  "education",
  "enterprise",
  "fintech",
  "logistics",
  "media-and-entertainment",
  "medical-and-healthcare",
  "ngo",
  "real-estate",
  "retail-and-manufacturing",
  "startup",
  "technology-company"
];
export function getIndustry(slug) {
  return INDUSTRY_DETAILS.find((i) => i.slug === slug) || null;
}
