/** Auto-generated by scripts/extract-industries.mjs */
export const INDUSTRIES_LANDING = {
  "hero": {
    "eyebrow": "Explore Our Expertise Across Diverse Industries!",
    "title": "Innovative Solutions for Your Industry",
    "description": "We deliver solutions designed to meet industry-specific needs and help you achieve your goals.",
    "image": "https://i.ibb.co.com/bH3K5FL/Rectangle-3843-2x.png",
    "ctaLabel": "Book A Consultation",
    "ctaHref": "/schedule-consultation"
  },
  "items": [
    {
      "slug": "fintech",
      "title": "Explore Fintech Solutions",
      "description": "Explore Fintech Solutions",
      "image": "",
      "href": "/industries/fintech"
    },
    {
      "slug": "startup",
      "title": "Explore Startup Solutions",
      "description": "Explore Startup Solutions",
      "image": "",
      "href": "/industries/startup"
    },
    {
      "slug": "logistics",
      "title": "Explore Logistics Solutions",
      "description": "Explore Logistics Solutions",
      "image": "",
      "href": "/industries/logistics"
    },
    {
      "slug": "retail-and-manufacturing",
      "title": "Explore Retail & Manufacturing Solutions",
      "description": "Explore Retail & Manufacturing Solutions",
      "image": "",
      "href": "/industries/retail-and-manufacturing"
    },
    {
      "slug": "enterprise",
      "title": "Explore Enterprise Solutions",
      "description": "Explore Enterprise Solutions",
      "image": "",
      "href": "/industries/enterprise"
    },
    {
      "slug": "education",
      "title": "Explore Education Solutions",
      "description": "Explore Education Solutions",
      "image": "",
      "href": "/industries/education"
    },
    {
      "slug": "real-estate",
      "title": "Explore Real Estate Solutions",
      "description": "Explore Real Estate Solutions",
      "image": "",
      "href": "/industries/real-estate"
    },
    {
      "slug": "medical-and-healthcare",
      "title": "Explore Medical & Healthcare Solutions",
      "description": "Explore Medical & Healthcare Solutions",
      "image": "",
      "href": "/industries/medical-and-healthcare"
    },
    {
      "slug": "technology-company",
      "title": "Explore Technology Company Solutions",
      "description": "Explore Technology Company Solutions",
      "image": "",
      "href": "/industries/technology-company"
    },
    {
      "slug": "media-and-entertainment",
      "title": "Explore Media & Entertainment Solutions",
      "description": "Explore Media & Entertainment Solutions",
      "image": "",
      "href": "/industries/media-and-entertainment"
    }
  ]
};
