import type { HeroContent, IndustryLandingItem } from "@/lib/types";

export const INDUSTRY_BRANDS = [
  { src: "/images/uber.png", alt: "Uber" },
  { src: "/images/Roche_brand.png", alt: "Roche" },
  { src: "/images/city_bank_brand.png", alt: "City Bank" },
  { src: "/images/robi_brand.png", alt: "Robi" },
  { src: "/images/care_brand.png", alt: "Care" },
  { src: "/images/unicef_brand.webp", alt: "UNICEF" },
  { src: "/images/macmillan_brand.png", alt: "Macmillan" },
  { src: "/images/world-health-organization_brand.webp", alt: "World Health Organization" },
];

export const INDUSTRIES_LANDING: { hero: HeroContent; items: IndustryLandingItem[] } = {
  hero: {
    eyebrow: "Explore Our Expertise Across Diverse Industries!",
    title: "Innovative Solutions for Your Industry",
    description:
      "We deliver solutions designed to meet industry-specific needs and help you achieve your goals.",
    image: "https://i.ibb.co.com/bH3K5FL/Rectangle-3843-2x.png",
    ctaLabel: "Book A Consultation",
    ctaHref: "/schedule-consultation",
  },
  items: [
    {
      slug: "fintech",
      title: "Fintech",
      description:
        "Drive innovation with secure, scalable, and customer-centric fintech solutions. From payment gateways to digital banking, empower your business with cutting-edge technology.",
      icon: "fa-solid fa-chart-area",
      href: "/industries/fintech",
      quote: {
        text: "The team's dedication and expertise in FinTech solutions were impressive, ensuring efficiency and keeping everyone aligned throughout the project",
        name: "Arif Al Zahin",
        role: "Assistant Manager at City Bank",
        avatar: "https://i.ibb.co.com/j9FXMCk2/city-bank-Assistant-Manager.jpg",
      },
      solutionsTitle: "Fintech Solutions We Deliver",
      solutions: [
        "Digital Payments Solutions",
        "Blockchain Technology Integration",
        "Mobile Banking Applications",
        "Peer-to-Peer Lending Platforms",
        "Wealth & Asset Management Tools",
        "Fraud Detection & Prevention Systems",
        "Cryptocurrency Platforms",
        "Regulatory Compliance Solutions",
      ],
      exploreLabel: "Explore Fintech Solutions",
    },
    {
      slug: "startup",
      title: "Startup",
      description:
        "Empower your startup with innovative solutions that drive growth and efficiency. From MVP development to scaling, we provide the tools you need to succeed.",
      icon: "fa-solid fa-lightbulb",
      href: "/industries/startup",
      quote: {
        text: "The team's innovative approach and commitment to developing tailored solutions helped us scale quickly and navigate early challenges with ease",
        name: "Tanvir Ahamad Fahim",
        role: "Customer Service Associate at Uber",
        avatar: "https://i.ibb.co.com/ZRM2N8jQ/uber-Customer-Service-Associate.jpg",
      },
      solutionsTitle: "Startup Solutions We Deliver",
      solutions: [
        "MVP Development",
        "Product Design & Prototyping",
        "Market Research & Analysis",
        "Growth Hacking Strategies",
        "Investor Pitch Decks",
        "Scalable Cloud Solutions",
        "Agile Development",
        "Startup Mentorship",
      ],
      exploreLabel: "Explore Startup Solutions",
    },
    {
      slug: "logistics",
      title: "Logistics",
      description:
        "Optimize your logistics operations with advanced technology solutions. From supply chain management to real-time tracking, enhance efficiency and reduce costs.",
      icon: "fa-solid fa-truck",
      href: "/industries/logistics",
      quote: {
        text: "The team's solutions significantly optimized our supply chain operations, improving delivery efficiency and reducing costs across the board",
        name: "Robert Green",
        role: "Logistics Manager at FastTrack Logistics",
        avatar: "https://i.ibb.co.com/rXHnBgs/logistic.png",
      },
      solutionsTitle: "Logistics Solutions We Deliver",
      solutions: [
        "Supply Chain Management",
        "Fleet Management Systems",
        "Inventory Tracking Solutions",
        "Real-Time Shipment Tracking",
        "Warehouse Management",
        "Route Optimization",
        "Logistics Analytics",
        "Automated Order Processing",
      ],
      exploreLabel: "Explore Logistics Solutions",
    },
    {
      slug: "retail-and-manufacturing",
      title: "Retail & Manufacturing",
      description:
        "Transform your retail and manufacturing processes with technology-driven solutions. From inventory management to customer engagement, drive growth and efficiency.",
      icon: "fa-solid fa-store",
      href: "/industries/retail-and-manufacturing",
      quote: {
        text: "Their industry-specific solutions streamlined our production processes, enhanced inventory management, and improved the overall customer experience",
        name: "Dewan Jamil",
        role: "Deputy Assistant Director at Walton",
        avatar: "https://i.ibb.co.com/HDhZjtWf/deputy-Walton.jpg",
      },
      solutionsTitle: "Retail & Manufacturing Solutions We Deliver",
      solutions: [
        "Inventory Management Systems",
        "Customer Relationship Management (CRM)",
        "Point of Sale (POS) Systems",
        "E-commerce Platforms",
        "Manufacturing Process Automation",
        "Supply Chain Optimization",
        "Retail Analytics",
        "Customer Engagement Solutions",
      ],
      exploreLabel: "Explore Retail & Manufacturing Solutions",
    },
    {
      slug: "enterprise",
      title: "Enterprise",
      description:
        "Empower your enterprise with scalable and secure technology solutions. From ERP systems to cloud computing, enhance productivity and drive innovation.",
      icon: "fa-solid fa-building",
      href: "/industries/enterprise",
      quote: {
        text: "The team's enterprise solutions enabled us to modernize our infrastructure, improve efficiency, and enhance collaboration across departments.",
        name: "James Black",
        role: "CIO at EnterpriseCorp",
        avatar: "https://i.ibb.co.com/jZqFP8HK/Meet-Maelle-scaled-1.jpg",
      },
      solutionsTitle: "Enterprise Solutions We Deliver",
      solutions: [
        "Enterprise Resource Planning (ERP)",
        "Business Intelligence & Analytics",
        "Cloud Computing Solutions",
        "Cybersecurity Services",
        "IT Infrastructure Management",
        "Enterprise Mobility Solutions",
        "Data Management & Integration",
        "Custom Software Development",
      ],
      exploreLabel: "Explore Enterprise Solutions",
    },
    {
      slug: "education",
      title: "Education",
      description:
        "Enhance the learning experience with innovative education technology solutions. From e-learning platforms to student management systems, empower educators and students.",
      icon: "fa-solid fa-graduation-cap",
      href: "/industries/education",
      quote: {
        text: "Their innovative educational technology solutions helped us enhance our learning platforms, making education more accessible and interactive for both students and teachers.",
        name: "Paolo Gallucci",
        role: "Editor & Copywriter at Macmillan Education",
        avatar: "https://i.ibb.co.com/BVLw1sbS/macmillan.jpg",
      },
      solutionsTitle: "Education Solutions We Deliver",
      solutions: [
        "E-learning Platforms",
        "Student Information Systems",
        "Learning Management Systems (LMS)",
        "Virtual Classrooms",
        "Educational Content Development",
        "Teacher Collaboration Tools",
        "Student Engagement Solutions",
        "Assessment & Evaluation Tools",
      ],
      exploreLabel: "Explore Education Solutions",
    },
    {
      slug: "real-estate",
      title: "Real Estate",
      description:
        "Revolutionize the real estate industry with technology solutions that enhance property management, sales, and customer engagement.",
      icon: "fa-solid fa-home",
      href: "/industries/real-estate",
      quote: {
        text: "The solutions provided have significantly improved our property management processes, enhanced customer relationships, and streamlined our real estate operations",
        name: "David Grey",
        role: "Real Estate Manager at RealEstatePro",
        avatar: "https://i.ibb.co.com/gZ5s9n11/uber-ceo.webp",
      },
      solutionsTitle: "Real Estate Solutions We Deliver",
      solutions: [
        "Property Management Systems",
        "Real Estate CRM",
        "Virtual Property Tours",
        "Online Booking & Scheduling",
        "Market Analysis & Insights",
        "Customer Engagement Solutions",
        "Investment Management Tools",
        "Real Estate Analytics",
      ],
      exploreLabel: "Explore Real Estate Solutions",
    },
    {
      slug: "medical-and-healthcare",
      title: "Medical & Healthcare",
      description:
        "Enhance healthcare delivery with advanced technology solutions. From telemedicine to patient management systems, improve patient care and operational efficiency.",
      icon: "fa-solid fa-heartbeat",
      href: "/industries/medical-and-healthcare",
      quote: {
        text: "Their healthcare technology solutions have greatly improved our ability to deliver efficient, high-quality care, significantly enhancing patient outcomes.",
        name: "Emma Brown",
        role: "Healthcare Administrator at HealthCarePlus",
        avatar: "https://i.ibb.co.com/jZqFP8HK/Meet-Maelle-scaled-1.jpg",
      },
      solutionsTitle: "Medical & Healthcare Solutions We Deliver",
      solutions: [
        "Telemedicine Solutions",
        "Electronic Health Records (EHR)",
        "Patient Management Systems",
        "Medical Billing & Coding",
        "Healthcare Analytics",
        "Remote Patient Monitoring",
        "Pharmacy Management Systems",
        "Healthcare Mobile Apps",
      ],
      exploreLabel: "Explore Medical & Healthcare Solutions",
    },
    {
      slug: "technology-company",
      title: "Technology Company",
      description:
        "Drive innovation with cutting-edge technology solutions. From software development to cloud computing, empower your tech company to achieve its goals.",
      icon: "fa-solid fa-laptop-code",
      href: "/industries/technology-company",
      quote: {
        text: "The innovative technology solutions provided helped us stay ahead of the curve, enabling us to scale efficiently and improve our overall product offerings.",
        name: "Chris White",
        role: "CTO at TechInnovate",
        avatar: "https://i.ibb.co.com/rXHnBgs/logistic.png",
      },
      solutionsTitle: "Technology Company Solutions We Deliver",
      solutions: [
        "Custom Software Development",
        "Cloud Computing Solutions",
        "AI & Machine Learning",
        "DevOps Services",
        "Cybersecurity Solutions",
        "Data Analytics & Visualization",
        "Mobile App Development",
        "IT Consulting & Strategy",
      ],
      exploreLabel: "Explore Technology Company Solutions",
    },
    {
      slug: "media-and-entertainment",
      title: "Media & Entertainment",
      description:
        "Transform the media and entertainment industry with innovative technology solutions. From content creation to distribution, enhance your audience's experience.",
      icon: "fa-solid fa-film",
      href: "/industries/media-and-entertainment",
      quote: {
        text: "Their digital solutions have transformed the way we engage with our audience, streamlining content delivery and enhancing interactivity",
        name: "Mahtab Uddin Ahmed",
        role: "Managing Director and CEO at Robi",
        avatar: "https://i.ibb.co.com/sJm4mL40/robi.png",
      },
      solutionsTitle: "Media & Entertainment Solutions We Deliver",
      solutions: [
        "Content Management Systems",
        "Digital Asset Management",
        "Video Streaming Solutions",
        "Social Media Integration",
        "Audience Analytics",
        "Interactive Media Solutions",
        "Virtual & Augmented Reality",
        "Media Production Tools",
      ],
      exploreLabel: "Explore Media & Entertainment Solutions",
    },
  ],
};
