/** Client logos used in the "Trusted by top brands" sections. */
export const BRANDS = [
  { src: "/images/uber.png", alt: "Uber" },
  { src: "/images/Roche_brand.png", alt: "Roche" },
  { src: "/images/city_bank_brand.png", alt: "City Bank" },
  { src: "/images/robi_brand.png", alt: "Robi" },
  { src: "/images/care_brand.png", alt: "CARE" },
  { src: "/images/unicef_brand.webp", alt: "UNICEF" },
  { src: "/images/macmillan_brand.png", alt: "Macmillan" },
  { src: "/images/world-health-organization_brand.webp", alt: "World Health Organization" },
  { src: "/images/ilo_brand.png", alt: "ILO" },
  { src: "/images/bell.png", alt: "Bell" },
  { src: "/images/uber.png", alt: "Uber" },
  { src: "/images/Roche_brand.png", alt: "Roche" },
  { src: "/images/city_bank_brand.png", alt: "City Bank" },
  { src: "/images/robi_brand.png", alt: "Robi" },
  { src: "/images/care_brand.png", alt: "CARE" },
  { src: "/images/unicef_brand.webp", alt: "UNICEF" },
  { src: "/images/macmillan_brand.png", alt: "Macmillan" },
  { src: "/images/world-health-organization_brand.webp", alt: "World Health Organization" },
  { src: "/images/ilo_brand.png", alt: "ILO" },
  { src: "/images/bell.png", alt: "Bell" },
  // { src: "/images/scb-logo.webp", alt: "Standard Chartered Bank" },
  // { src: "/images/usaid_brand.png", alt: "USAID" },
  // { src: "/images/sage-brand.png", alt: "Sage" },
  // { src: "/images/keller-williams.png", alt: "Keller Williams" },
  // { src: "/images/hydro-one-telecom-logo.png", alt: "Hydro One Telecom" },
  // { src: "/images/FAO_logo_brand.png", alt: "FAO" },
  // { src: "/images/ada-grp.webp", alt: "ADA Group" },
  // { src: "/images/berger.png", alt: "Berger" },
  // { src: "/images/walton.png", alt: "Walton" },
  // { src: "/images/kocsitem-logo.webp", alt: "Kocsitem" },
];

export const BRANDS_2ND = [
  { src: "/images/usaid_brand.png", alt: "USAID" },
  { src: "/images/sage-brand.png", alt: "Sage" },
  { src: "/images/hydro-one-telecom-logo.png", alt: "Hydro One Telecom" },
  { src: "/images/keller-williams.png", alt: "Keller Williams" },
  { src: "/images/FAO_logo_brand.png", alt: "FAO" },
  { src: "/images/ada-grp.webp", alt: "ADA Group" },
  { src: "/images/berger.png", alt: "Berger" },
  { src: "/images/walton.png", alt: "Walton" },
  { src: "/images/kocsitem-logo.webp", alt: "Kocsitem" },
  { src: "/images/usaid_brand.png", alt: "USAID" },
  { src: "/images/sage-brand.png", alt: "Sage" },
  { src: "/images/hydro-one-telecom-logo.png", alt: "Hydro One Telecom" },
  { src: "/images/keller-williams.png", alt: "Keller Williams" },
  { src: "/images/FAO_logo_brand.png", alt: "FAO" },
  { src: "/images/ada-grp.webp", alt: "ADA Group" },
  { src: "/images/berger.png", alt: "Berger" },
  { src: "/images/walton.png", alt: "Walton" },
  { src: "/images/kocsitem-logo.webp", alt: "Kocsitem" },
]
