/**
 * Recovery generator.
 *
 * Reads the original static export (../*.html) and regenerates the Next.js
 * App Router source:
 *   - components/header.content.js  (shared mega-menu markup)
 *   - app/<route>/content.js        (per-page recovered markup)
 *   - app/<route>/page.jsx          (route entry + metadata)
 *   - app/not-found.jsx             (from _not-found.html)
 *
 * Header + footer blocks are stripped from each page because they are rendered
 * as real components in app/layout.jsx.
 *
 * Run from the web_frontend directory:  node scripts/recover.mjs
 */
import { parse } from "node-html-parser";
import fs from "node:fs";
import path from "node:path";

const OUT_DIR = path.resolve(process.cwd(), "..");
const APP_DIR = path.resolve(process.cwd(), "app");
const COMPONENTS_DIR = path.resolve(process.cwd(), "components");

const SKIP = new Set(["404.html", "_not-found.html"]);

function collectHtmlFiles(dir, base = dir, acc = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "web_frontend" || entry.name === ".formatted" || entry.name === "node_modules") continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      collectHtmlFiles(full, base, acc);
    } else if (entry.name.endsWith(".html")) {
      acc.push(path.relative(base, full));
    }
  }
  return acc;
}

function isElement(node) {
  return node && node.tagName;
}

const IGNORE_TAGS = new Set(["SCRIPT", "NOSCRIPT", "TEMPLATE", "STYLE", "LINK"]);

function isIgnorable(node) {
  if (!isElement(node)) return true;
  if (IGNORE_TAGS.has(node.tagName)) return true;
  const cls = (node.getAttribute && node.getAttribute("class")) || "";
  if (cls.split(/\s+/).includes("Toastify")) return true;
  return false;
}

function extractParts(html) {
  const root = parse(html, { comment: false, blockTextElements: { script: false, style: false } });
  const body = root.querySelector("body");
  const children = body.childNodes.filter(isElement);

  const headerIdx = children.findIndex((n) => n.querySelector && n.querySelector("nav.nav"));
  const footerIdx = children.findIndex((n) => n.querySelector && n.querySelector("#page-footer"));

  const headerHtml = headerIdx >= 0 ? children[headerIdx].outerHTML : "";

  const start = headerIdx >= 0 ? headerIdx + 1 : 0;
  const end = footerIdx >= 0 ? footerIdx : children.length;
  const contentNodes = children.slice(start, end).filter((n) => !isIgnorable(n));
  const contentHtml = contentNodes.map((n) => n.outerHTML).join("\n");

  const head = root.querySelector("head");
  const title = head?.querySelector("title")?.text?.trim() || "";
  const description =
    head?.querySelector('meta[name="description"]')?.getAttribute("content") || "";

  return { headerHtml, contentHtml, title, description };
}

function routeFromFile(rel) {
  const noExt = rel.replace(/\.html$/, "").replace(/\\/g, "/");
  if (noExt === "index") return "";
  return noExt;
}

function writeModule(filePath, html) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `// Auto-generated by scripts/recover.mjs — recovered page markup.\nexport default ${JSON.stringify(html)};\n`);
}

function pageSource(route, title, description) {
  const canonical = "/" + route;
  const meta = {
    title: title || undefined,
    description: description || undefined,
    alternates: { canonical: route === "" ? "/" : canonical },
  };
  return `import RecoveredHtml from "@/components/RecoveredHtml";
import content from "./content.js";

export const metadata = ${JSON.stringify(meta, null, 2)};

export default function Page() {
  return <RecoveredHtml html={content} />;
}
`;
}

function main() {
  const files = collectHtmlFiles(OUT_DIR);
  let headerWritten = false;
  let count = 0;

  // Prefer index.html for the shared header fragment.
  const ordered = files.sort((a) => (a === "index.html" ? -1 : 1));

  for (const rel of ordered) {
    const base = path.basename(rel);
    const html = fs.readFileSync(path.join(OUT_DIR, rel), "utf8");
    const { headerHtml, contentHtml, title, description } = extractParts(html);

    if (!headerWritten && headerHtml) {
      writeModule(path.join(COMPONENTS_DIR, "header.content.js"), headerHtml);
      headerWritten = true;
    }

    if (base === "_not-found.html") {
      writeModule(path.join(APP_DIR, "not-found.content.js"), contentHtml);
      fs.writeFileSync(
        path.join(APP_DIR, "not-found.jsx"),
        `import RecoveredHtml from "@/components/RecoveredHtml";\nimport content from "./not-found.content.js";\n\nexport const metadata = { title: ${JSON.stringify(title || "Page not found")} };\n\nexport default function NotFound() {\n  return <RecoveredHtml html={content} />;\n}\n`
      );
      count++;
      continue;
    }

    if (SKIP.has(base) || base === "not-found.html") continue;

    const route = routeFromFile(rel);
    const dir = route === "" ? APP_DIR : path.join(APP_DIR, route);
    writeModule(path.join(dir, "content.js"), contentHtml);
    fs.writeFileSync(path.join(dir, "page.jsx"), pageSource(route, title, description));
    count++;
  }

  console.log(`Recovered ${count} routes. Header fragment written: ${headerWritten}`);
}

main();
