/** Auto-generated by scripts/extract-home.mjs */
export const HOME_HERO = {
  "title": "Building Scalable Software & Teams That Drive Growth",
  "description": "Flyte Solutions is a custom software development company specializing in IT staff augmentation, MVP development, and SaaS application development. We help startups, SMEs, and enterprises hire skilled remote developers to build scalable, secure, and high-performance digital products."
};

export const HOME_BANNER_INDUSTRIES = [
  {
    "href": "/industries/fintech",
    "icon": "fa-solid fa-chart-area",
    "label": "Fintech"
  },
  {
    "href": "/industries/education",
    "icon": "fa-solid fa-graduation-cap",
    "label": "Education"
  },
  {
    "href": "/industries/logistics",
    "icon": "fa-solid fa-truck",
    "label": "Logistics"
  },
  {
    "href": "/industries/retail-and-manufacturing",
    "icon": "fa-solid fa-store",
    "label": "Retail & Manufacturing"
  },
  {
    "href": "/industries/real-estate",
    "icon": "fa-solid fa-building",
    "label": "Real Estate"
  },
  {
    "href": "/industries/medical-and-healthcare",
    "icon": "fa-solid fa-heart-pulse",
    "label": "Medical & Healthcare"
  },
  {
    "href": "/industries/technology-company",
    "icon": "fa-solid fa-microchip",
    "label": "Technology Company"
  },
  {
    "href": "/industries/media-and-entertainment",
    "icon": "fa-solid fa-video",
    "label": "Media & Entertainment"
  }
];

export const HOME_ABOUT = {
  "eyebrow": "About Company",
  "title": "Solutions That Drive Your Business Forward",
  "description": "Flyte Solutions offers custom software development, IT staff augmentation, and MVP development services to help you launch faster and scale smarter. From SaaS application development to dedicated remote development teams, we deliver secure, scalable, and cost-effective solutions for startups, SMEs, and enterprises worldwide.",
  "stats": [
    {
      "value": "12+",
      "label": "Years Experience",
      "icon": "https://i.ibb.co.com/wN59CwQ/flat-color-icons-calendar.png"
    },
    {
      "value": "350+",
      "label": "Projects Completed",
      "icon": "https://i.ibb.co.com/3N1bD6Y/fxemoji-clipboard.png"
    },
    {
      "value": "97%",
      "label": "Recurring Clients",
      "icon": "https://i.ibb.co.com/CBFFjvr/emojione-handshake.png"
    },
    {
      "value": "500+",
      "label": "Solutions Delivered",
      "icon": "https://i.ibb.co.com/wcBcfyL/twemoji-delivery-truck.png"
    }
  ]
};

export const HOME_SERVICES = [
  {
    "href": "/hire",
    "icon": "fa-solid fa-users text-xl",
    "title": "Team Extension",
    "description": "Expand your development capabilities with dedicated teams that integrate seamlessly with your existing operations."
  },
  {
    "href": "services/custom-software-development",
    "icon": "fa-solid fa-cogs text-xl",
    "title": "Custom Software Development",
    "description": "Tailored software solutions that align with your business needs, ensuring seamless integration and efficiency."
  },
  {
    "href": "services/enterprise-software-development",
    "icon": "fa-solid fa-chart-column text-xl",
    "title": "Enterprise Software Development",
    "description": "Build robust enterprise-level software to support large-scale operations, improve efficiency, and foster innovation."
  },
  {
    "href": "services/mobile-app-development",
    "icon": "fa-solid fa-mobile-screen text-xl",
    "title": "Mobile App Development",
    "description": "Design and develop mobile apps for iOS & Android, improving user experience and engagement."
  },
  {
    "href": "services/qa-and-testing",
    "icon": "fa-solid fa-shield-halved text-xl",
    "title": "Quality Assurance & Testing",
    "description": "Ensure software quality with comprehensive testing services, from functional to performance testing."
  },
  {
    "href": "services/mvp-development",
    "icon": "fa-solid fa-rocket text-xl",
    "title": "MVP Development",
    "description": "Build a minimum viable product quickly to test your ideas, validate concepts, and enter the market faster."
  }
];

export const HOME_AI_ML = {
  "eyebrow": "AI & ML",
  "title": "The New Era of Artificial Intelligence",
  "image": "/images/ai-and-ml-senction-image.png",
  "headline": "Small Language Models (SLM) are the future of humanity.",
  "description": "In our cooperative agreement with frontier R&D corp Autonomo FZCO, we provide cutting-edge SLM and LLM-powered solutions.",
  "bullets": [
    "Dynamic web app creation, live, in-browser",
    "Autonomous translation of your websites and documents into 28+ languages",
    "Voice-first APIs and web interfaces",
    "And much more..."
  ],
  "benefits": [
    {
      "icon": "fa-solid fa-info text-white text-xs lg:text-base",
      "title": "Total Privacy",
      "description": "Your data stays on your systems."
    },
    {
      "icon": "fa-solid fa-dollar-sign text-white text-xs lg:text-base",
      "title": "Cost Effective",
      "description": "A fraction of the cost of LLMs."
    },
    {
      "icon": "fa-solid fa-user-group text-white text-xs lg:text-base",
      "title": "Collection of Experts",
      "description": "30+ digital minds to fit your needs."
    },
    {
      "icon": "fa-solid fa-lock text-white text-xs lg:text-base",
      "title": "No Vendor Lock-in",
      "description": "Open-source models with full commercial rights."
    },
    {
      "icon": "fa-solid fa-globe text-white text-xs lg:text-base",
      "title": "No Country Lock-in",
      "description": "Host anywhere: USA, Europe, UAE, Asia."
    }
  ]
};

export const HOME_INDUSTRY_TABS = [
  {
    "icon": "text-lg fa-solid fa-gauge",
    "label": "Fintech",
    "slug": "fintech",
    "href": "/industries/fintech"
  },
  {
    "icon": "text-lg fas fa-lightbulb",
    "label": "Startup",
    "slug": "startup",
    "href": "/industries/startup"
  },
  {
    "icon": "text-lg fas fa-truck",
    "label": "Logistics",
    "slug": "logistics",
    "href": "/industries/logistics"
  },
  {
    "icon": "text-lg fas fa-store",
    "label": "Retail & Manufacturing",
    "slug": "retail-and-manufacturing",
    "href": "/industries/retail-and-manufacturing"
  },
  {
    "icon": "text-lg fas fa-building",
    "label": "Enterprise",
    "slug": "enterprise",
    "href": "/industries/enterprise"
  },
  {
    "icon": "text-lg fas fa-graduation-cap",
    "label": "Education",
    "slug": "education",
    "href": "/industries/education"
  },
  {
    "icon": "text-lg fas fa-home",
    "label": "Real Estate",
    "slug": "real-estate",
    "href": "/industries/real-estate"
  },
  {
    "icon": "text-lg fas fa-heartbeat",
    "label": "Medical & Healthcare",
    "slug": "medical-and-healthcare",
    "href": "/industries/medical-and-healthcare"
  },
  {
    "icon": "text-lg fas fa-laptop-code",
    "label": "Technology Company",
    "slug": "technology-company",
    "href": "/industries/technology-company"
  },
  {
    "icon": "text-lg fas fa-film",
    "label": "Media & Entertainment",
    "slug": "media-and-entertainment",
    "href": "/industries/media-and-entertainment"
  },
  {
    "icon": "text-lg fas fa-hand-holding-heart",
    "label": "NGO",
    "slug": "ngo",
    "href": "/industries/ngo"
  }
];

export const HOME_FINTECH_FEATURES = [
  {
    "icon": "fa-regular fa-star text-[#4D6AFF] text-2xl",
    "title": "Mortgage Software Development",
    "description": "Custom platforms that automate loan origination and underwriting, improving the borrower journey while ensuring full compliance and scalability."
  },
  {
    "icon": "fa-regular fa-credit-card text-[#4D6AFF] text-2xl",
    "title": "Lending Software Development",
    "description": "Build intuitive investment tools featuring real-time analytics, automated portfolio management, and seamless integration with market data sources."
  },
  {
    "icon": "fas fa-chart-line text-[#4D6AFF] text-2xl",
    "title": "Investment Software Development",
    "description": "End-to-end digital lending solutions that simplify onboarding, credit assessment, and loan management—secure, scalable, and user-focused."
  },
  {
    "icon": "fas fa-shield-alt text-[#4D6AFF] text-2xl",
    "title": "InsurTech Software Development",
    "description": "Digital insurance platforms that modernize policy management, accelerate claims processing, and enhance customer engagement through automation."
  },
  {
    "icon": "fas fa-lock text-[#4D6AFF] text-2xl",
    "title": "Payment Software Development Services",
    "description": "Secure, scalable payment systems with multi-currency and gateway support, fraud prevention, and seamless integration."
  }
];
